### ISSUE TITLE
P1 Completion 2/13 _ Correction to MSF Contacts 

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#102]
Phase 1 Completion Requirement 2/13 

The MSF requirements for Contacts is limited to 5 fields for the table, and the same 5 fields for the hover/one click quick view of the Contact details on the map:

Name / Email / Phone / Type / Affiliation / Speciality

**Comment by matthewberryman** [comment]
Speciality hasn't previously been captured. Opening a new ticket for that.

**Comment by matthewberryman** [comment]
done, table needs a UI tweak per #116

**Comment by LucieGueuning** [comment]
- Missing affiliation on the quick view
- only view on map and not on table.

Need to be re-open

**Comment by matthewberryman** [comment]
I had affiliation present in both the table and on the map, although it was listed as "Type", not "Affiliation" (but it was correct on the contact input cards).  I have removed it from the table as per your updated request. Changes will be deployed in ~5 mins from now.

**Comment by LucieGueuning** [comment]
@anexact

**Comment by LucieGueuning** [comment]
misunderstanding. sorry for that.
'I have removed it from the table as per your updated request.' My request was saying that we are seeing that 'affiliation' field on table but should have it. 

could you please add : 'affiliation' on table and map linked to the column L of spreadsheet. 

Thanks!

**Comment by matthewberryman** [comment]
Table not quite right.

**Comment by LucieGueuning** [comment]
@matthewberryman Perfect! Thanks!
