### ISSUE TITLE
P1 Completion 3/13 _ Contacts Search

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#103]
Phase 1 Completion Requirement 3/13

MSF requires a Search function for Contacts at the Event Level.

<img width="1181" alt="screen shot 2017-09-03 at 9 24 10 am" src="https://user-images.githubusercontent.com/20785542/30001291-c0ef4a3e-9089-11e7-8bef-28d332c1704b.png">

**Comment by matthewberryman** [comment]
@talltom please help with API side

**Comment by matthewberryman** [comment]
@talltom did some work on this in https://github.com/MSFREACH/msf-reach/commit/aee331f585be6eab2590337767faa2b0f471dd91 
cc @rcdelfin

**Comment by matthewberryman** [comment]
The new API in aee331f (dev branch) mandates search. I would argue we also still want the option of all contacts being returned, and can we also have the option of searching within radius of the event? @talltom

**Comment by mehrdadgit** [comment]
The issue of mandating the search fixed in 8856cf644cee0fd9282bb323434e686a0d1d5cf1 
Also contact search functionality done; although some UI improvement can be done later.

**Comment by matthewberryman** [comment]
Done but needs UI fix per https://github.com/MSFREACH/msf-reach/pull/121/files#r140177661 (I will open another ticket for that). cc @LucieGueuning @anexact
