### ISSUE TITLE
P1 Completion 5/13 _ Mission History Search 

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#105]
Phase 1 Completion Requirement 5 / 13

MSF requires a Search bar function on the Mission history on all Event sublevels.

<img width="1215" alt="screen shot 2017-09-03 at 9 44 09 am" src="https://user-images.githubusercontent.com/20785542/30001372-8c0ee45c-908c-11e7-9da1-d1a658c65565.png">

**Comment by matthewberryman** [comment]
@talltom please assist with API changes

**Comment by matthewberryman** [comment]
works but just noting #122 cc @LucieGueuning
