### ISSUE TITLE
P1 Completion 6/13 _ Mission History Details

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#106]
Phase 1 Completion Requirement 6/13

MSF require a Mission History Details popup from either table or map hover/double click; Note: same UX pop-up as in https://github.com/usergroupcoop/msf-reach/issues/104.

LG will add the minimum viable list of details for such a Missions Details pop-up to the comment section below.

**Comment by LucieGueuning** [comment]
Sorry for the delay. 
Please find below the minimum viable list of details for Missions Details pop-up. You can follow the following picture to display those information in an efficient way (to avoid a bullet point list, use the collapse and extend function per category. Cf. below).
![mission history details - popup windows](https://user-images.githubusercontent.com/25951555/30464580-e0311cb8-9a04-11e7-85c6-d68824012a85.PNG)

Agree @clgeros ?

**Category 1 : Basic Information**
Event Name
Open Date of event
Closure Date of event
Status
Type of Emergency (nature)
Precise location of the emergency
Date and hours (local time) of the disaster
Mission Contact Person
Main results of the explo-mission
Analysis of severity
Security information
ID link - SharePoint

**Category 2 : MSF Response**
MSF response / type of programmes
Start Date of the MSF response
End Date of the MSF response
Location of MSF response
Operational Center
Medical material
Non medical material

**Category 3 : External Capacity**
Analysis of capacity on the ground
Other organizations, partners involved
Deployment
Date of arrival

**Category 4: Key Figures**
Figures
Population in total for zone impacted
population affected
Pourcentage of people affected
Key MSF Figures

**Category 5 : MSF Resources**
Staffs list _ Human ressources supply
Exapt
National staff
When were they hired by MSF? / When do they arrive on the ground?
Category
Name
Function
Contact number
Comments/Evaluation
Visa requirement
Budget
Institutional Donors

**Category 6: Reflection and comments**
Practical Details / Recommendations
Reflection / Comments on intervention
 
/ Relevant Contacts (linked to the location of event)
/ Relevant Mission History (linked to the location of event)
/ Relevant Reports by categories (4) + when do they arrive? after event was open? before event was open?
access
needs
contacts
security
/ Relevant news from the social medias AND news medias : which info/post/tweet were selected when monitoring?

**Comment by matthewberryman** [comment]
Thanks @LucieGueuning

**Comment by LucieGueuning** [comment]
Note that 'Category 1 : Basic information' is the black box on picture. 
/ relevant contacts + / relevant mission history are showed on map
/ relevant reports are the ones upper left corner on picture

Other category are the ones which can be collapse and extent below 'reports' category on picture.

**Comment by matthewberryman** [comment]
vue.min.js:6 Error: Map container not found.
    at e._initContainer (leaflet.js:2)
    at e.initialize (leaflet.js:1)
    at new e (leaflet.js:1)
    at Object.Ct [as map] (leaflet.js:1)
    at $e.<anonymous> (<anonymous>:48:25)
    at Array.<anonymous> (vue.min.js:6)
    at t (vue.min.js:6)
    at <anonymous>

**Comment by matthewberryman** [comment]
vue.min.js:6 TypeError: Cannot read property 'arrival_time' of undefined
    at $e.eval (eval at Ii (vue.min.js:6), <anonymous>:2:1176)
    at $e.t._render (vue.min.js:6)
    at $e.r (vue.min.js:6)
    at zo.get (vue.min.js:6)
    at new zo (vue.min.js:6)
    at Ct (vue.min.js:6)
    at $e.$mount (vue.min.js:6)
    at $e.$mount (vue.min.js:6)
    at $e.t._init (vue.min.js:6)
    at new $e (vue.min.js:6)
