### ISSUE TITLE
P1 Completion 11/13 _ Security reports distinction

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#111]
Phase 1 Completion Requirement 11/13

Because Security threats are a top priority for Operators, MSF requires that the "Security" reports (i.e. cards that are submitted with the "Security" tag selected by users) be graphically distinguished  on the map. 

In their design ethnography, CG and LG used an exclamation point over top of the pin to make this distinction, but this is a poor UX decision and will scale poorly. Require a new solution via color, size, or other feature to make this distinction for completion of Phase 1.

**Comment by matthewberryman** [comment]
I've done the coding work for this just require icons—can someone please email asap. Ping @LucieGueuning @clgeros @anexact

**Comment by clgeros** [comment]
@matthewberryman 
New Report Icons can be found here: https://drive.google.com/drive/folders/0Bw27FPU-gFxYMVo3ZERwRnNDTDQ?usp=sharing

YELLOW = SECURITY
RED = ACCESS 
BLUE = NEEDS
GREEN = CONTACTS
BLACK = UNDESIGNATED
