### ISSUE TITLE
P1 Completion 12/13 _ Report categorization

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#112]
Phase 1 Completion Requirement 12/13

MSF requires that reports can be categorized by type for the Operator; while all report types would load automatically, request is to add 4 types to the map legend which could be turned off:
Security
Needs
Access
Contact
<img width="680" alt="screen shot 2017-09-03 at 10 12 27 am" src="https://user-images.githubusercontent.com/20785542/30001505-b9e79e56-9090-11e7-8b2c-ba1a9c991feb.png">

**Comment by matthewberryman** [comment]
@LucieGueuning I have implemented this—are you happy with the look and feel of it, for this issue?
If so, let me know, and I can close this one off.

Some of the work I've done here also contributed to #111—I just need to drop the separate icon in for that.

**Comment by matthewberryman** [comment]
Closing this as I consider it done, and would like to track progress towards the milestone. @LucieGueuning if you're unhappy with UI then feel free to re-open the issue.

**Comment by LucieGueuning** [comment]
@matthewberryman I would like to re-open this issue but it seems that I don't have the permission. Could you please help me with that? 

What you have done is perfect, only one requirement to improve it : 
Could you please on legend/menu add 'reports' on same level than 'contacts' and 'mission histories' and put 'access', 'needs', 'security' and 'contacts' as subcategories? You can remove 'reports' words for each of the 4 sub-categories. 
![image](https://user-images.githubusercontent.com/25951555/30465461-e379b89e-9a09-11e7-9e60-e82a92c4b0ce.png)

![image](https://user-images.githubusercontent.com/25951555/30465528-2c7e9280-9a0a-11e7-94f8-d2912e709609.png)

Thanks
