### ISSUE TITLE
P1 Completion 13/13 _ MSF Testing

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#113]
Phase 1 Completion Requirement 13/13

To complete contractual obligations for Phase 1, MSF HK Operator will test the Phase 1 Completed Prototype from 9 - 20 October, and then send feedback to User for any final issues (no NEW issues) on 20 October.

Please add comments on this issue thread for MSF Operators re: testing questions, updates, concerns, or other issues that exceed any specific issue threads and ET will rely in meeting prior to testing.

**Comment by matthewberryman** [comment]
@LucieGueuning if you're happy I've captured everything please close this issue, and then we are just tracking the others.
