### ISSUE TITLE
Layout tweaks

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#116]
* Can we squish the email column in the table of contacts on events page, to make sure all 5 required columns per https://github.com/MSFREACH/msf-reach/issues/102 fit in
* The addition of map search can break the layout of contacts and report cards on mobile devices if a user starts to use the map search.

**Comment by matthewberryman** [comment]
* Ok I'm happy with adjustment to email column fix as is.
* On my iPhone the buttons are right up against the map. Can we make the map just a bit smaller still to leave a small gap? Once you've done this @mehrdadgit please let us know and I would like @talltom and @anexact to check on their devices just so we do a bit of testing on different devices, before we close.

**Comment by mehrdadgit** [comment]
Done @matthewberryman we might need to rethink the design of these cards for phase 2 ...

**Comment by matthewberryman** [comment]
Opening to track changes to update new UI elements to make them work on mobile devices.

**Comment by matthewberryman** [comment]
Two remaining issues: 
1. country row column not removed (noting that country field not displayed for items) in order to avoid wrapping
2. on tablet, selection field not wide enough.
![img_0108](https://user-images.githubusercontent.com/2288238/49400616-e098cc80-f798-11e8-9762-a591713b791c.jpg)
