### ISSUE TITLE
Contact us button on log in page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#119]
Could you please add a button under the log in field on log in page as below? 
When clicking on button 'contact us', user will have a pop-up window ready to write me an email. 

![image](https://user-images.githubusercontent.com/25951555/30477488-f141299a-9a3f-11e7-8985-a4fef628ab58.png)

**Comment by LucieGueuning** [comment]
BTW, I don't have permission to assign the issue to someone or to input it to milestones - Phase 1
@matthewberryman

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/30477586-3dc9cb6e-9a40-11e7-9ea0-707eb877cfe2.png)
Those are not editable for me anymore! :(

**Comment by anexact** [comment]
Hi Lucie,
The discussion we had was to include the written email address on the page for people who wanted to contact MSF HK, not a button for email. However, as this was not on our HK list after the Demo, let's move it to Phase 2.

**Comment by LucieGueuning** [comment]
Is a button really difficult and take time to input (one line code no?)? It will be waste of time if I request to write my email (one line code) and to change it one month later for a button no?

Could you do the necessary for this small point? I guess we remove already a lot from the expectations for Phase 1 (UX and so on), isn't it?

**Comment by matthewberryman** [comment]
It's a few lines of code, but correct me if I'm wrong that this wasn't on the list for phase 1, and we have other UI changes (per https://github.com/MSFREACH/msf-reach/issues/102#issuecomment-330461684 removing it from the table) and new issues #120 being added with limited time to get this all done

**Comment by LucieGueuning** [comment]
Yes you are right, it wasn't on the list for phase 1. I received this request after our presentation coming from EUROPE. I didn't expect that neither. Sorry about that. 
We didn't get the time to review and work (as contract said) on UI and UX at all because of delay. So I try to prioritize my best to make it possible for 09 of Oct.
Let me know if not possible at all. Thank you for your reply.

**Comment by LucieGueuning** [comment]
@anexact
