### ISSUE TITLE
UI fix for events page

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#122]
col sizes in divs out of date with js in public/events/index.html , also map is at the bottom with the changes in https://github.com/MSFREACH/msf-reach/pull/121 
https://github.com/MSFREACH/msf-reach/pull/121/files#r140177661
cc @LucieGueuning

**Comment by mehrdadgit** [comment]
Done @matthewberryman

**Comment by matthewberryman** [comment]
Thanks @mehrdadgit
