### ISSUE TITLE
map tweaks for #109 #110

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#126]
* add some padding (by points / by latlng extension with wrap?) to cover a wider area than bbox formed by set of reports, to bring in more mission histories and contacts that might be relevant. 
*don't pan to popup to avoid set of contacts and mission histories changing.

**Comment by matthewberryman** [comment]
tag #109 #110

**Comment by matthewberryman** [comment]
could do by changing zoom level too

**Comment by LucieGueuning** [comment]
Can we close that off? still need to work on it? @matthewberryman
