### ISSUE TITLE
mouseover bug in #101

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#129]
In latest work for #101 I have a bug in the function to highlight a div element on mouseover of a hazard, in the section starting https://github.com/MSFREACH/msf-reach/blob/master/public/resources/js/landing.js#L316
I will have time for a brief look tomorrow, but can you please check this out.
It would also be good to highlight div elements of the rss table on mouseover, in particular to help indicate that the divs themselves can be clicked on to take you to the feed item on the map.

**Comment by mehrdadgit** [comment]
see a sample fix @matthewberryman  here: https://github.com/MSFREACH/msf-reach/commit/735298303e0cfadbe2cfa39f01acf9393b04aa99  need to expand to other cases; heading home now will do tonight.
