### ISSUE TITLE
fix map controls for mission and contacts layers on events page

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#130]
https://github.com/MSFREACH/msf-reach/issues/82#issuecomment-336039712

cc @LucieGueuning

**Comment by matthewberryman** [comment]
I’ve been struggling with the same issue on #134 as I need to update the events layer (also a geoJSON layer); the fix seems to be to just replace the data per https://github.com/Leaflet/Leaflet/issues/1416#issuecomment-13778453 - I will have a go at this on both of these issues when I get back home.

**Comment by matthewberryman** [comment]
Actually this is slightly different to #134; here simply keeping state on whether or not the control's been added (as I had to do in #134, but in #134 I also had to update the layer too) will fix the bug.

**Comment by matthewberryman** [comment]
Nope, not quite, per comment I just added on #134 the control gets out of sync.

**Comment by matthewberryman** [comment]
Keeping track of this control issue here.
I'm first trying to remove the layer, to remove the old control, however it's failing with
```
```
due to a bug in leaflet-groupedlayercontrol, https://github.com/ismyrnow/leaflet-groupedlayercontrol/issues/49 , which won't be completely fixed until https://github.com/ismyrnow/leaflet-groupedlayercontrol/pull/46 is merged (the pull request fixes the bug but also introduces a new feature). I will have to separately fork and patch.

**Comment by LucieGueuning** [comment]
No auto sync when creating an event. Still need to refresh to see our event on homepage.

**Comment by LucieGueuning** [comment]
Mission and RSS feed are not on event as layer ON/OFF

**Comment by matthewberryman** [comment]
The event refresh is a separate issue https://github.com/MSFREACH/msf-reach/issues/134
and a map control for RSS feeds is a separate issue https://github.com/MSFREACH/msf-reach/issues/212 (and separately syncing map and table is https://github.com/MSFREACH/msf-reach/issues/175 ). Just noting that the controls do work, and the current issue here is that the contacts / missions come back on when the map is panned or zoomed.
