### ISSUE TITLE
do not require user to refresh to see new event

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#134]
On event creation automatically add it to events list on events page by rewriting that content (or if that's too much trouble, auto refresh the page).

**Comment by matthewberryman** [comment]
Because the new event opens in a new tab #49 (and then reloads the event page in that tab on event creation) we have no way of communicating back to the landing page tab. I am currently working on refreshing the events every minute to keep it reasonably up to date.

**Comment by matthewberryman** [comment]
@LucieGueuning I'm just about to push a fix that refreshes the events on the map and table every three minutes. Unfortunately a deeper fix to get it to show immediately will require a redesign of the UX and quite a lot of work. I have gone with three minutes as the table and map need to be redrawn, and if the user has a popup open it will close it, so keeping the refresh period longer minimises the chance of the user losing their place. In developing that fix, I encountered the same bug as https://github.com/MSFREACH/msf-reach/issues/130 and so I now know how to fix that one, which I will do next.

**Comment by matthewberryman** [comment]
layerControl is kept but doesn't turn off the new layer

**Comment by LucieGueuning** [comment]
No auto sync when creating an event. Still need to refresh to see our event on homepage.

**Comment by matthewberryman** [comment]
We cannot auto-sync across two tabs as we have it now, so I have set a periodic refresh for phase 1. We will need to explore this as part of overall redesign for phase 2.

**Comment by matthewberryman** [comment]
Events now show up instantly on the landing page, and similarly for reports on the events page.
