### ISSUE TITLE
search on more contact fields

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#140]
in particular for suppliers
EDIT: suppliers in type (affiliation) json field

**Comment by matthewberryman** [comment]
Note sorting on different columns and column display more generally to be worked on in phase 2.

**Comment by matthewberryman** [comment]
have expanded to type (affiliation) and speciality fields, consistent with columns. I would argue that we don't want to expand to all fields because (1) they're not displayed and (2) can slow down performance.

**Comment by LucieGueuning** [comment]
Need to be able to filter by suppliers. Not search by into an open search box - free text.

**Comment by matthewberryman** [comment]
1. We don't have a separate field for suppliers, instead we have a category field (we can revisit in https://github.com/MSFREACH/msf-reach/issues/179 if need be but I think category covers it) 
2. We could add a checkbox to select only suppliers based on category field (something to look at in https://github.com/MSFREACH/msf-reach/issues/194 )

**Comment by LucieGueuning** [comment]
Now we have a category 'supplier' which allows us to proceed

**Comment by matthewberryman** [comment]
Just about to add a bunch of others (email, etc.) with exclusion of web and social media. I've broken off the search by category as a drop down selection.
