### ISSUE TITLE
change default zoom of map

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#141]
to open Asia-wide

**Comment by LucieGueuning** [comment]
When creating an event also

**Comment by matthewberryman** [comment]
Also will do contact card too

**Comment by matthewberryman** [comment]
Now requested that we open centred on SE Asia, not Asia.

**Comment by matthewberryman** [comment]
@anexact note this is now in our dev environment. I will open a separate issue for map snapping to force it to SE Asia / other UX options.
