### ISSUE TITLE
sometimes tables and map out of sync

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#143]
Note in attached image for example how there's one on the map but two on the table. See if we can close this by phase 1 deadline (Oct 30)
![picture 3](https://user-images.githubusercontent.com/2288238/31745793-07fa850c-b4b0-11e7-96e6-2162f0a69090.PNG)

**Comment by mehrdadgit** [comment]
@matthewberryman I think I had noticed it and my theory is that 2 contacts have exact same lat/lng so the marker icons are placed on top of each other; one solution is clustering ( had done some testing here in a separate branch : https://github.com/MSFREACH/msf-reach/commit/42e76ff79e154bf84bda9506a230560b64e238b9 )  although not sure how much work is needed for that; I could give it a go by tomorrow ?

**Comment by matthewberryman** [comment]
Yes give it a go (please keep in separate branch and submit pull request when ready).

Sent from my iPhone

On 29 Oct 2017, at 21:27, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


@matthewberryman<https://github.com/matthewberryman> I think I had noticed it and my theory is that 2 contacts have exact same lat/lng so the marker icons are placed on top of each other; one solution is clustering ( had done some testing here in a separate branch : 42e76ff<https://github.com/MSFREACH/msf-reach/commit/42e76ff79e154bf84bda9506a230560b64e238b9> ) although not sure how much work is needed for that; I could give it a go by tomorrow ?

**Comment by mehrdadgit** [comment]
@matthewberryman this should be done now as we have merged clustering?
