### ISSUE TITLE
re-auth

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#144]
When the token expires, it can show as a 401 error on API calls, and rather than popping up a window we should direct user to login page and then back to the page the 401 popped up on.
See if we can close by phase 1 deadline (Oct 30).

![picture 2](https://user-images.githubusercontent.com/2288238/31745885-56685c00-b4b0-11e7-8fc5-4640b0d067f6.PNG)

**Comment by matthewberryman** [comment]
Noting there's an alert() for missions errors at present (that needs to be changed) but we also need to capture errors on contacts (GET method) and events and reports (GET method) errors.

**Comment by mehrdadgit** [comment]
a fix is in; the only issue at the moment being that page might show several error messages (coming from multiple ajax calls) before redirecting the user to login page; can be fixed...

**Comment by matthewberryman** [comment]
@mehrdadgit going with @rcdelfin's solution here, I am just adding in some stuff to make the alerts clearer and will commit + push soon.

**Comment by matthewberryman** [comment]
Sometimes get a couple of alerts but works.
