### ISSUE TITLE
event creation box on landing page should have calendar for date input

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#146]
rather than pre-populating with current date and time

**Comment by mehrdadgit** [comment]
@matthewberryman just confirming that you mean "Date/time of Event" on New Event page https://www.msf-reach.org/events/new/  ? cause I cannot find event creation box on 'landing' page

**Comment by matthewberryman** [comment]
The one under toolbox -> create new event.

Sent from my iPhone

On 22 Oct 2017, at 14:37, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


@matthewberryman<https://github.com/matthewberryman> just confirming that you mean "Date/time of Event" on New Event page https://www.msf-reach.org/events/new/ ? cause I cannot find event creation box on 'landing' page

**Comment by mehrdadgit** [comment]
Yep that one is just a link to create new event page; done now; 
And I removed "time" cause jquery ui datepicker does not support time; please review and close if all OK .

**Comment by matthewberryman** [comment]
Ok I am out today will review tomorrow. Thanks :)

Sent from my iPhone

On 22 Oct 2017, at 15:04, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep that one is just a link to create new event page; done now;
And I removed "time" cause jquery ui datepicker does not support time; please review and close if all OK .

**Comment by matthewberryman** [comment]
@LucieGueuning Just noting that I have updated the display on landing page (table and map) plus events page to display this date / date as edited on #108 - not always consistent in date format, will fix per https://github.com/MSFREACH/msf-reach/issues/159
