### ISSUE TITLE
tweet save functionality not working

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#151]
Looks like bugs elsewhere (e.g. below) are killing the JS engine before the load saved tweets code runs.
```
events.js:85 Uncaught TypeError: Cannot read property 'nonMedicalMaterials' of undefined
    at unpackMetadata (events.js:85)
    at printEventProperties (events.js:176)
    at Object.success (events.js:209)
    at i (jquery-3.2.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js:2)
    at A (jquery-3.2.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js:4)
```

**Comment by LucieGueuning** [comment]
Do not work when come back on homepage

**Comment by matthewberryman** [comment]
I fixed the problem that was preventing saves altogether and I am seeing correct behaviour on the events page but it does take a minute (configurable) for the saved tweets to show up, after saving them, as there's caching at the web server level. I can turn off the caching at the web server level or reduce the duration but would rather not as it will degrade performance a bit.

**Comment by LucieGueuning** [comment]
still bug!

**Comment by matthewberryman** [comment]
With https://github.com/MSFREACH/msf-reach/commit/8ddf2d91be42ceacff3301859d0b582276630d9d and https://github.com/MSFREACH/msf-reach/commit/780c7051ca27c56d58c87d24f6f3ca4ccc8a7f87 this is now working for me in the dev environment. @LucieGueuning when we merge our development branch of the code back into the master branch it will automatically fix in production environment, but until then it won't be fixed there, only in dev.

**Comment by LucieGueuning** [comment]
Not working on prod. When can you fix it for Natasha?

**Comment by matthewberryman** [comment]
This is working on prod now, following a merge of the fix earlier today - just tested it then. Note due to caching it can take a minute or two to show up (we can change configuration of delay as noted previously)

**Comment by matthewberryman** [comment]
update on this - 
Bug remains fixed (just tested and this is saving tweets), but
1. I have turned off cache, so they show up a bit sooner, though at some point on prod I will have to turn cache back on. 
2. There was a separate error message showing up on save for some events that I am just fixing now on prod and dev, related to chatbot integration, but this wasn't preventing tweets from being saved.

**Comment by matthewberryman** [comment]
working for me; to help diagnose Natasha's issue further I need to know tweet she's trying to save, web browser version and operating system version.

**Comment by matthewberryman** [comment]
closing this in favour of #263
