### ISSUE TITLE
mandatory contact fields

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#155]
Make sure the following and only the following are mandatory fields for a contact card:
* Phone number
* Email address
* Location 
 - if street address is given then prompt but don't force it <- new behaviour
 - make sure at least a point location is mandatory.

For mandatory fields add a red star next to them, and then at the bottom add a note
` * Mandatory fields. Other fields optional.`

cc @LucieGueuning to double check on specifications for this

**Comment by LucieGueuning** [comment]
Could you please quickly add a red star for location of map? Thanks

**Comment by LucieGueuning** [comment]
great!
