### ISSUE TITLE
settle on date format to be used

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#159]

**Comment by matthewberryman** [comment]
@anexact

**Comment by anexact** [comment]
<img width="662" alt="date time view" src="https://user-images.githubusercontent.com/20785542/38473445-7d0322b6-3b90-11e8-8953-03c684743c7b.png">
Can we display Date and Time view as above?

**Comment by matthewberryman** [comment]
I've gone with .toLocaleString() that generates a format consistent with computer settings (so varies from computer to computer) but omits seconds. The event creation box (per screenshot in previous commit) needs to have the yyyy-mm-dd shown and as it goes in and comes out it's actually per operator TZ so I've changed wording, but then I'm happy with that one being different as it's entered by sliders that make it clear anyway, along with initial placeholder.
