### ISSUE TITLE
event creation from map

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#180]
Rather than toolbox linking to separate page, have popup forms on map, with two options:
* Create from (RSS feed derived) hazard/disaster
* Free choice.

Also support creation from new report not linked to existing event

**Comment by LucieGueuning** [comment]
thanks to a box? if I have no idea about the precise location?

**Comment by matthewberryman** [comment]
I've got a note in a commit I'm just about to deploy, that the location can be approximate, when double clicking to select a location (anywhere on the map, could be on an RSS feed event or somewhere else)—we will in future work support editing of location plus event page has had some tweaks anyway in #305 to make it more box-like.

**Comment by matthewberryman** [comment]
I think this is done. Could consider the mechanism (currently double click / double tap) for opening for map if people have problems with that but closing for now.
