### ISSUE TITLE
Machine learning and prediction for mission planning

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#182]

**Comment by LucieGueuning** [comment]
A low hanging fruit is if we had numerical data on supplies sent out for different types of events, along with numerical data on population affected, then it’s very easy to build a predictive model for future events.

I had a look at https://docs.google.com/spreadsheets/d/1AzlyOrAD3zFjdvTTvfMwEnRR9wpp3H6wT-ay2LpkLuE/edit#gid=1233626802 and the data is written in text form, and there’s not nearly enough there for us to train a model on.

Something to consider in ethnography.

**Comment by matthewberryman** [comment]
In addition to looking at back-filling above mission histories with data, we can also generate fake data for development and testing (and then in production will slowly learn on event archive -> past missions). To do that I need an idea of what fields we want to learn on (suppliers, etc.) and what a typical _range_ of data looks like for that. 

Also, as part of ethnography work to go into https://github.com/MSFREACH/msf-reach/issues/194, need to think about UX for this - maybe a popup window with details of predictions for event creation, or could pre-fill the event details (but then would need to change the event fields on event creation established in #179 )

Fake data on dev side to showcase how AI/ML can work with proper data (input fake data) to make life easier. System need to learn from data. Right suggestion of suppliers, what was the response in the past if ....
On landing page, on prod side, pop window with security items.
@lucie : in addition to that, need to find more data regarding past responses.

**Comment by LucieGueuning** [comment]
AI/ML, as per discussion with Etienne, should also be a smart search function for mission history and twitter (linked to the specific request/needs of the user).

**Comment by matthewberryman** [comment]
In absence of ethnographic feedback (outlined to come in part 2 of contract) and sample data for this major feature, changing milestone.

**Comment by LucieGueuning** [comment]
As per our discussion, two developments:

Fake data on dev side to showcase how AI/ML can work with proper data (input fake data) to make life easier. System need to learn from data. Right suggestion of suppliers, what was the response in the past if ....
On landing page, on prod side, pop window with security items.
@lucie : in addition to that, need to find more data regarding past responses.

**Comment by LucieGueuning** [comment]
Mobile phones and other ICTs for data collection are already key components in humanitarian response and international development programs. Adding algorithms and automation through machine learning and deep learning allows us to identify patterns in the data that can inform decisions and real-time analysis.

**Comment by matthewberryman** [comment]
Basic support done, suggestions for particular fields part of #537
