### ISSUE TITLE
life layers

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#184]
medical infrastructure etc. drawing from OSM projects + other sources

**Comment by anexact** [comment]
Currently in conversation with OSM about available data sets; can update and add to Phase 2 depending on availability and quality of data & relevance to MSF.

**Comment by matthewberryman** [comment]
@anexact let's leave this open until you can report back on conversation and (if there are some datasets to be added) until we've got them in MSF-REACH

**Comment by matthewberryman** [comment]
Is this not a duplicate of https://github.com/MSFREACH/msf-reach/issues/255 ?

**Comment by matthewberryman** [comment]
Duplicate of 255
