### ISSUE TITLE
search contacts on landing page

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#185]

**Comment by LucieGueuning** [comment]
@matthewberryman : Ah yes, sorry was part of this feature, my mistake! 

As per email: Re. contact search, the user requires, in addition to the results shown on the map, the results shown on the table below the search function. Can it be like the same feature than on the event page: having the contacts on the map shown on table and synchronise based on the map zoom?

Many thanks.

**Comment by matthewberryman** [comment]
We have search supported already, closing. Addition of table is #408. I'll get that done asap but need feedback.

**Comment by LucieGueuning** [comment]
I am sorry Matthew but the search today is almost done but not exactly we expected. So #408 needs to be part of this phase 2a - part 2. 

Could you please change the milestone of #408 to Phase 2a - part 2 (feedback from regional training). 

Thanks for understanding.

**Comment by matthewberryman** [comment]
The searching functionality is complete. The display of search results can be changed but it's well past the deadline agreed in writing to specify this for phase 2a- part two.
