### ISSUE TITLE
verification status of reports

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#190]

**Comment by LucieGueuning** [comment]
by operators

**Comment by matthewberryman** [comment]
@talltom I think we need some API changes here similar to contacts
1. PATCH not PUT
2. Make subroutes for report status type and contents (so I don't have to update contents just for a report status type) and just noting on contents here and contact cards it's desirable to not have to update the jsonb field as a whole, only by particular key(s).

**Comment by matthewberryman** [comment]
@talltom API is fine as is. Will push a commit soon after a little bit more testing. cc @LucieGueuning
