### ISSUE TITLE
icon legend

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#192]

**Comment by LucieGueuning** [comment]
to be add on 'info' tabs on landing page

**Comment by matthewberryman** [comment]
Needs to go on all pages, which we could put on a modal that opens from a menu item under the session menu. Should we also have OSM legend #241 in same place?

**Comment by matthewberryman** [comment]
Can you use a cookie (note we're using [js-cookie](https://github.com/js-cookie/js-cookie)) so that once toggled off it will stay off over page reload (or load of map on different page).
