### ISSUE TITLE
geocoding of events, missions -> countries

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#195]
has cost and privacy implications to be discussed @LucieGueuning

**Comment by matthewberryman** [comment]
@LucieGueuning are you happy for the locations to go through Google for geocoding?
I can do the the past events and also geocode any changes, to address the comment from Natasha "In the “country” field, it says “undefined” and there is no space to edit it."  but need a decision from you on this.

**Comment by LucieGueuning** [comment]
as per discussion on skype call, I agree but need to be part of our presentation on Monday 19th of March. @matthewberryman to share that info with them. You can get ready with one slide re: developments and features on REACH (+live demo of the progress).

**Comment by matthewberryman** [comment]
This is done bar me going back for already imported missions—I will need to update my [script](https://github.com/MSFREACH/msf-reach-schema/blob/master/etl/geocode_existing_events.js).
