### ISSUE TITLE
make contact fields editable by operator

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#197]

**Comment by LucieGueuning** [comment]
need to know automatically when and who was the last contact with this person regarding a specific event.

**Comment by matthewberryman** [comment]
Please work on this in contacts branch for now, I would like to review client and API changes together tomorrow.

Sent from my iPhone

On 21 Jan 2018, at 13:46, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


Can start this as soon as the API is merged in 'dev'

**Comment by matthewberryman** [comment]
Make sure that operators can also delete records (so I guess we need a DELETE API ping @talltom )

**Comment by talltom** [comment]
Delete endpoint now operational (authenticated endpoint). Changes made to `contacts` branch which is up to date with `dev`.

See dbd6364420a656081d0f33dab16b28a2128763d9

**Comment by mehrdadgit** [comment]
Done on landing page contacts modal and in issues/174 branch; needs operator with write permission for testing.
