### ISSUE TITLE
searchable events map

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#198]
unless we get rid of events page #194

**Comment by matthewberryman** [comment]
@mehrdadgit @talltom we need to update the events API to be able to search for events

**Comment by matthewberryman** [comment]
@LucieGueuning ready for testing in dev

**Comment by matthewberryman** [comment]
I’ll add opened as well; in that case the date is filtered by the separate creation date.
In the Interim can you please test the rest of the functionality.

Sent from my iPhone

On 14 Nov 2018, at 05:27, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://user-images.githubusercontent.com/25951555/48434466-ac218a00-e771-11e8-9833-de1fae62b578.png>

[image]<https://user-images.githubusercontent.com/25951555/48434506-c78c9500-e771-11e8-91b4-f7c53c5a2fb3.png>

no result as there is one event related to conflict after the 18th of nov.

**Comment by LucieGueuning** [comment]
- same issue than above: no result for something that is existing. I think the issue is the keywords and not the date filtering. Need to search in other field, in addition to the name field. Type field should also be searchable. this is the reason conflict doesn't show up. It is because there no word conflict in the name. 

![image](https://user-images.githubusercontent.com/25951555/48489440-fc085b80-e81a-11e8-97b5-8df46cfa084a.png)

**Comment by matthewberryman** [comment]
[image1.png]

I had type(s) and subtype(s) in the code already. I will double check what is going on in the morning.

Sent from my iPhone

On 15 Nov 2018, at 01:40, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


  *   same issue than above: no result for something that is existing. I think the issue is the keywords and not the date filtering. Need to search in other field, in addition to the name field. Type field should also be searchable. this is the reason conflict doesn't show up. It is because there no word conflict in the name.

[image]<https://user-images.githubusercontent.com/25951555/48489440-fc085b80-e81a-11e8-97b5-8df46cfa084a.png>

**Comment by matthewberryman** [comment]
@LucieGueuning there were some cases where type wasn't being searched properly due to previous changes in fields. Now fixed.
