### ISSUE TITLE
sub-events

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#204]
discuss and think about implementing:
When different OC's are going to intervene for the same emergency for different field (surgery OR supply OR Water and Sanitation), we should have the ability to separate one event into different sub-event.

**Comment by anexact** [comment]
The sub-division of the event would also need to go the other way, i.e. aggregation. However, from ethnography it is clear that the most consistent data structure for deployment is the budget code; perhaps once explo/intervention occurs, the budget code should be logged as a key element in the data / archive.

**Comment by LucieGueuning** [comment]
I correct from 'budget code' to 'Project Code' as consistent data structure for deployment

**Comment by matthewberryman** [comment]
Addition of project code covered by https://github.com/MSFREACH/msf-reach/issues/272
Event aggregation appears to be covered in work in #30 and related issues. So I think we can close this one @LucieGueuning ?
