### ISSUE TITLE
some overlay icons missing...

### ISSUE THREAD

**Issue by mehrdadgit** [MSFREACH/msf-reach#206]
![image](https://user-images.githubusercontent.com/7603978/32760963-e1d156a4-c944-11e7-9f55-526527929845.png)

**Comment by mehrdadgit** [comment]
@matthewberryman could you point me to SVG folder on google drive? are they really missing or we have no svg file for them yet ?

**Comment by matthewberryman** [comment]
Dupe of https://github.com/MSFREACH/msf-reach/issues/63 (icons used across hazards RSS feeds are missing some hazard types)- google drive folder on that issue.
