### ISSUE TITLE
same map everywhere

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#212]

**Comment by matthewberryman** [comment]
Just checked and realised we do have map controls for RSS feeds (a group with individual controls for particular feeds) on landing page. On events page we don't have RSS at all. Do we want that? @LucieGueuning

**Comment by LucieGueuning** [comment]
Yes we want the same map everywhere. 

Also, instead of 'Hazards', it should be RSS Feeds
