### ISSUE TITLE
API changes for contacts schema PR

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#219]
https://github.com/MSFREACH/msf-reach-schema/pull/25

**Comment by matthewberryman** [comment]
@talltom please do this work in the [contacts branch](https://github.com/MSFREACH/msf-reach/tree/contacts)

**Comment by matthewberryman** [comment]
@LucieGueuning this behind the scenes work is done (thanks @talltom for his help) and @mehrdadgit has made these fields displayable on the large modal popup (on events page go to contacts table and click on "eye"). 
There's #227 and #197 that @mehrdadgit will work on.
Tomorrow I will work on the popup displays on the maps and also review the input fields on the contacts cards and work on that.

**Comment by LucieGueuning** [comment]
Great! Let me know once it is done and I will then share the final version for people to continue to enter their contact information through our REACH contact card.
