### ISSUE TITLE
GDPR  exercise

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#225]
From Matthew: having read that in conjunction with other rules and regulations and contracts (one of which I will need to sign and send to AWS before I can commence) I can now proceed to set up development (dev) and production (prod) environments.

I reviewed both the GDPR rules from the EU web site in addition to the AWS compliance documents and provided my company has signed the agreement with AWS to abide by EU rules (signed and submitted as of yesterday) then I am satisfied it is fine.

**Comment by LucieGueuning** [comment]
The dev site is now up at https://dev.msf-reach.org/ 
It is pointing at a separate copy of the database that I made from a snapshot before I removed some of the test events from the prod database underlying https://msf-reach.org/

Notes for all: as they’re using different databases, new events / contacts/ reports added to one will not show in the other (by design). I haven’t had time for much testing as this has taken quite a while (why I wanted to wait for GDPR report to come in). I will do some more testing of our dev environment tomorrow.

**Comment by LucieGueuning** [comment]
I’ve now completed the migration of the production environment https://msf-reach.org/ and also fixed a networking glitch that was causing some speed issues on first page load of the development environment https://dev.msf-reach.org/ , plus update the chatbot links to point to the development environment for now. Any issues / questions just ask.

**Comment by LucieGueuning** [comment]
Thanks for your hard work on that @matthewberryman

**Comment by matthewberryman** [comment]
There are some follow up activities for me to look at this week to make sure from the report that we're fully compliant in terms of UX and data storage and flows. One notable thing that we're missing is the option for people to be able to edit / remove their contact information, #227

**Comment by LucieGueuning** [comment]
working on GDPR Report

**Comment by LucieGueuning** [comment]
FYI, those are the three issues to be fixed within REACH platform to be compliant to the GDPR
![image](https://user-images.githubusercontent.com/25951555/37786851-962ae7f4-2df5-11e8-88e9-02e96e2802e9.png)

**Comment by LucieGueuning** [comment]
- possible to remove entirely contacts details from our entire system? without MB
- consent to use data for our purposes (to be explained)
- from a to z, need to know where their data goes
- all contacts because MSF is organisational based in Europe. 

prove that you are doing an effort and give enough information to the person.

**Comment by matthewberryman** [comment]
@LucieGueuning , @mehrdadgit is working on the contact editing and removal steps, I will shortly document where data goes, but reminder that from you I urgently need privacy policy (to go up on a page I can link to from first contact card, please copy and paste into a comment here) - and also the name and contact details of the MSF Data Protection Officer (email those)

**Comment by matthewberryman** [comment]
following on from my previous comment I found the privacy policy and now link directly to that
