### ISSUE TITLE
option for contacts to edit or remove their contact information

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#227]
I'm about to push some boilerplate stuff for nodemailer for you to work from. You'd need to have an option on the first contact card to submit an email address for update, and then the server sends an email with a link to a page for editing only that specific user.

**Comment by matthewberryman** [comment]
Matthew to
1. Set up DNS entries for mail for msf-reach.org domain.
2. Set up admin@msf-reach.org email
3. Send SMTP user and pass credentials to @mehrdadgit 

@mehrdadgit to work on the rest

**Comment by mehrdadgit** [comment]
@matthewberryman so this needs for all contacts have unique email addresses ? so would need to check for duplicate email when adding new contact as well ? If so, we may need to get email on the first page of contact card to alert ("user already exist") then, if email already exists,  we can ask "do you want to update this user ?"

Also, thinking that  we need sth like a uuid key in contacts table.. for saving and emailing it to the user (as the GET param of update URL) to be a bit secure? If not, we can just send the contact id? what do you think ?

**Comment by matthewberryman** [comment]
I think adding a UUID as well as ID is best (although someone can't guess ID, they could use it to figure out how many entries in the database). 

The trouble with alerting people is that someone else could interrogate the system to see if someone else's email is in the system even though they can't edit the record or see the rest. I guess we could allow someone to complete the card again and then if the primary or secondary email address match any email address on file (i.e. primary entered matches primary or secondary on file, or secondary matches primary or secondary on file) then on POST (rather than silently doing a different request client side which again could be detected), the server can send an email saying do you wish to update and with a link that then PATCHes the existing record. 

@talltom thoughts and help please.

**Comment by LucieGueuning** [comment]
(not sure this is the right issue). as per discussion on skype

Two steps for updating contacts info. Need to be both completed to keep contact on the platform
1. Email automatic after 6 months of inactivity on REACH to ask whether their contact information have changed or are still correct (need to pro-actively confirm by actions). 
1.1 second email for remind them and let them know that they contact info will be deleted from our REACH platform if they are not confirming or updating their contact information. 
2. flag to operators, contacts who haven't action after 2 emails of reminder for updating contact info.

**Comment by matthewberryman** [comment]
@talltom can you please provide an update on this

**Comment by matthewberryman** [comment]
@LucieGueuning The plan for this is for updates for be emailed every 6th months (with reminders as per your comment); in addition contacts should be able to update their details at any time. @talltom can you please provide an update asap on API & DB support for this

**Comment by matthewberryman** [comment]
@talltom can you please provide an update on this urgently? Please submit a PR when done in contacts branches here and on msf-reach-schema

**Comment by LucieGueuning** [comment]
Please note that the following email addresses was not delivered for different reasons: the recipient's email system refuse to accept a connection from our email system (cf. emails list by email).

**Comment by talltom** [comment]
@matthewberryman - this PR merges the contacts branch for server code into dev.

https://github.com/MSFREACH/msf-reach/pull/377

**Comment by matthewberryman** [comment]
Thanks @talltom - I have pushed some changes 
1. Align joi with latest requirements around fields & contact input UI as to what's required. I could probably tighten a few up.
2. peers -> update change (it's not just peers but any contact that we need to update)
3. Allow for checking against 

@mehrdadgit can you now work on UI for this? Just noting as well as client side work for updating and deleting contact info you'll also need to fill in the email template for node mailer, put that on a 6 month schedule, and also in the case that a 409 error is returned, update the error message to say "your email is already listed in our system, would you like to update or delete your details?" and then email link for updating/deleting. I'll make sure you have the latest credentials for email after I double check tomorrow.

**Comment by matthewberryman** [comment]
@mehrdadgit continue work in contacts branch for this, please

**Comment by LucieGueuning** [comment]
Contacts, able to edit their profile such as **example** (UI) below: 
![profile to edit](https://user-images.githubusercontent.com/25951555/39509766-53cf89a0-4ddf-11e8-8e5e-4bafd4ec7dae.jpg)

**Comment by mehrdadgit** [comment]
@matthewberryman ready for testing; note still did not get to fully retrieve "Type of Contact" card for edit ;(will fix tomorrow) but everything else should work fine.

**Comment by LucieGueuning** [comment]
Can we add at the end of the first submission of contact card one sentence to inform people how they can edit/remove their contact information. 

If you would like to edit or remove your contact information, please click on this link and add your email address. 

Something like that. 

Thanks
