### ISSUE TITLE
contact card completion checklist

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#231]
1. ~~Still awaiting @LucieGueuning and @anexact to solve category/type issue https://github.com/MSFREACH/msf-reach/issues/179#issuecomment-359635079~~
2. ~~@matthewberryman to work on form validation of email and phone number #229~~ 
3. @talltom [optional but nice to have re 5.] any progress on API validation of required fields? Also be sure to review and close off already completed issues (e.g. #218 ).
4. @LucieGueuning @mehrdadgit @matthewberryman Review of UX and fix of bugs (e.g. https://github.com/MSFREACH/msf-reach/issues/230 ).
5. @LucieGueuning to input some data into dev so we ( @matthewberryman @talltom @mehrdadgit ) can double check that it's going in to the database Ok and fix any identified bugs.
6. Pull request to merge to master (and hence into prod).

**Comment by LucieGueuning** [comment]
1. solved
4. waiting for your green light since everything is ready from your side on dev environment. @mehrdadgit @matthewberryman @talltom 
5. waiting for your green light to add contact for testing on dev environment.

**Comment by matthewberryman** [comment]
1. See comment on other thread
2. That issue will close off automatically when it gets merged to dev, along with the rest once we've finalised contact cards. 
I think you mean 5. - best to wait until we think we've finalised everything in dev.

**Comment by matthewberryman** [comment]
@LucieGueuning @mehrdadgit now ready for to you review the UX and also put some information in on dev (starting in 5 minutes from time of me writing this comment, to allow time for build and deployment) for testing. Once that starts going in I will check in the database. Once @LucieGueuning is happy with the fields on the contacts cards, I will then proceed with work on the corresponding display changes on the landing and events pages for contacts along with other types of information, as well as working on scripts to (re-)import supplied contact information.

**Comment by mehrdadgit** [comment]
regarding point 4: above fixes are in and on dev

**Comment by LucieGueuning** [comment]
Feedback on contact cards: 
1. *Mandatory fields. Other fields **are** optional. (Please add the word 'are'). 
2. 'Association member' needs to be a check box options as 'MSF peers'. 'Supplier' can be removed and become one of the category options. 
3. 'Other' need to have a field to specify (on category option).
4. Add 'Job title' field to fill in by the user.
5. Remove OCA as a first choice on dropdown for MSF staff only. LEt it blank (political reasons).
6. Replace 'International Office' by 'IO'
7. Remove s from Mission. Sorry my mistake.
8. Add 'Website' and 'Fax' field after phone number and email address
9. Phone need to be optional field
10. Remove the dot after location (map driven slide). Sentence need to be: 'Please enter your current home address'.
11. on first slide, add a dot after 'indicates mandatory fields.'
12. on 'contact details' slide, please center the '*Mandatory fields. Other fields **are** optional.'
13. on 'type of contact' slide, current employment status for MSF staff needs to be the second field and not the third one. 
14. Please follow exactly (order and spelling) the spreadsheet for small map popup contact details. 
15. on contact modal, spelling mistake (I think). filled time*

**QUESTION**: How to ensure the private and public contact filled by MSF staff on contact modal (per users log in). Public ones are the ones who filled in their contact information. Someone who fill info for someone else need to be private to this specific log in. MSF staff can make a contact public but need to have a popup message saying that: 'by doing that, they have verified and got approval from the contact to be shared with the whole MSF worldwide'. Should we have two different contacts cards: one filled by MSF staff into the system once they have logged in - one to share with public to fill in their own contact details? Good solution? @matthewberryman @anexact

**Comment by LucieGueuning** [comment]
Need to have a double-check + test entries through the dev env. before going live into prod env.

**Comment by matthewberryman** [comment]
I've crossed off the ones I've done.
For item 10, we didn't require home address, only location (that can be manually adjusted) for security and privacy reasons. 
For 15 both "filed" and "filled" work. I would argue "filed" is closer in meaning to what this field is actually showing, which is the date that contact was first entered into the system. I would actually propose changing this to "date first entered".

**Comment by matthewberryman** [comment]
10. Going with "Please enter your home address or pin your home location" to permit option but to emphasise location (if just pin entered) should be home location and not another location.
15. Going with "Created on:" and updating other times to say "on" as well, for consistency.

**Comment by matthewberryman** [comment]
Per discussion, if person entering data is an operator (can detect cookie) then:
* Can have tick box to say they have permission from contact, and could display separate policy if required.
* I will also flag those in the database as well, for reference.

**Comment by LucieGueuning** [comment]
Feedback: 
- Gender shouldn't be mandatory
- 'Phone' word missing
- 'Fax', 'Website' missing
- Sentence of mandatory field should be centre on contact details slide.

**Comment by LucieGueuning** [comment]
I am waiting for having the tick box thanks to cookies before entering data for testing + improvements from my last feedback just up there

**Comment by matthewberryman** [comment]
The fields for fax and website were there and as well as the text in the box I have added some text similar to the fields for "email" outside of the boxes. Note that to fit this all in for mobile I had to remove space between related inputs (i.e. all of the phone inputs are now closely grouped together).

I have also added a tick box that is shown - remind operators to log in, and it will keep track of that over a couple of days (rather than requiring users to log in every hour) and present the tick box in that case, but not to anyone else. I've also added a line in the code that makes a field in the database if it was operator entered or not.

@LucieGueuning Since all the fields are in, if there are further cosmetic issues like spacing, wording, etc. then you can still proceed with testing while waiting for these fixes.

**Comment by LucieGueuning** [comment]
@mehrdadgit, I need your help to test the contact cards on dev site to try all scenarios and possibilities. Thanks!

**Comment by LucieGueuning** [comment]
@matthewberryman Feedack 3 (shoul dbe the last one from my side):
- first slide: update my email by 'Please contact us for any ...' and hyperlink with mailto:lucie.gueuning@hongkong.msf.org
- contact details slide: need to center the line with mandatory field....

Thanks. After that, I am happy with the contact cards and want to have it at your soonest migrate to prod env.

**Comment by matthewberryman** [comment]
@LucieGueuning we've tested that records are going in to the database Ok.
I also fixed a few UI things - have tagged you on these. Have merged this in along with other changes (event table scrolling, event input modal incl. a fix to that https://github.com/MSFREACH/msf-reach/commit/bfe342aee24216796bacd41ad3c80545e726f4a1 ).

**Comment by matthewberryman** [comment]
@LucieGueuning Just double checking that you want to leave category as a non-mandatory field? And regardless of whether you want that non-mandatory or mandatory, if someone selects category of "Other", do you want to make them type something in for what that other category is?

If you want to leave it as it is now (where neither is required) then I need to update some display code tomorrow my time to fix this, although you can start to enter in data. Otherwise I can push a fix tonight my time to make them mandatory.

**Comment by LucieGueuning** [comment]
For category, we keep it as a non-mandatory field. And if user selects 'Other', then a field for typing what this other is needs to appear. Make sense?

**Comment by matthewberryman** [comment]
Yes - I have the other field for "other" popping up if so, does it need to be filled in or can it be left blank? I can add a check for this if it needs to be filled in.

**Comment by matthewberryman** [comment]
per whatsapp discussion - all optional

**Comment by matthewberryman** [comment]
Ok that case is now handled. There are still some other minor display things for me to double check tomorrow (mainly around old data we imported, which we also need to revisit), along with double checking fields for events and reports.

**Comment by LucieGueuning** [comment]
@matthewberryman 
- current employment status (when choosing 'MSF current staff' for category), needs to display 'Please select' and not 'field worker...'.

**Comment by LucieGueuning** [comment]
Have now applied that fix to handle empty type cases. I made a few configuration changes on the back end for a smoother upgrade of dev, given you may be using it, but if your connection had any issues, that’s why. I will follow up on GH
