### ISSUE TITLE
no separate page for event & support this as option for report creation

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#238]
On the landing page, have a modal for creation of new events, and on the events page have the option of a modal for new reports; this solves https://github.com/MSFREACH/msf-reach/issues/134. Note that for new reports we need to have an option of modal for operators but still have a link that can be copied and pasted / sent out automatically from chatbot.

**Comment by matthewberryman** [comment]
(changed title to make it clear that work on report creation modal is not optional, it's that the display of the modal is an option)

**Comment by matthewberryman** [comment]
@mehrdadgit Please help me fix
* General style issues on reports modal
* [Scroll](https://github.com/MSFREACH/msf-reach/blob/reports_modal/public/events/index.html#L103) not working.
* [This function](https://github.com/MSFREACH/msf-reach/blob/reports_modal/public/resources/js/new-report.js#L32) is missing a call to reset the report type on modal close.

**Comment by mehrdadgit** [comment]
@matthewberryman had a look; needs a bit of design thinking imo. for example, I think it would be nicer to make it with prev/next buttons similar to report card but with a white background and different design...if no rush, leave this with me, to do it properly by early next week.

**Comment by mehrdadgit** [comment]
Done @matthewberryman feel free to review and merge to dev. Let me know if you want any style change.

**Comment by matthewberryman** [comment]
@LucieGueuning please try this out - I have tried it out on dev and after confirming it was working there have put it in prod too

**Comment by LucieGueuning** [comment]
Working. Thanks.
