### ISSUE TITLE
restrict RSS entries to Asia

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#243]

**Comment by LucieGueuning** [comment]
Natasha flag a RSS from Greece. Makes sure it is only for Asia. 

FYI, in the near future, with AD, we will attribute location preferences for people who are monitoring America for example. Make sense?

**Comment by matthewberryman** [comment]
From email:
RSS items are only shown for hazards in Asia (and occasionally some in Europe and Africa, as I’ve done this by setting up a rectangular bounding box - hard to avoid this without a lot of work geocoding the events and storing in database).

**Comment by matthewberryman** [comment]
I could refine in phase 2a part 2. I will set up a different issue for per operator regions.

**Comment by LucieGueuning** [comment]
linked to #57

**Comment by matthewberryman** [comment]
RSS feeds are restricted so this work is done. Other areas covered by https://github.com/MSFREACH/msf-reach/issues/416 https://github.com/MSFREACH/msf-reach/issues/455 etc.
