### ISSUE TITLE
event update tracking

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#251]
I have thought a bit about event notification tracking through time. I could make this metadata field a list (would also require a SQL patch to upgrade old events per https://github.com/MSFREACH/msf-reach-schema/issues/29), and will start on some small modifications to client side code tomorrow, but:
There's a broader issue of whether we need to keep a history of changes to all fields and how we might display that and use it as part of ML.

**Comment by matthewberryman** [comment]
Working, looks like the following. Waiting on @talltom https://github.com/MSFREACH/msf-reach-schema/issues/29 before merging into dev. cc @LucieGueuning 

<img width="676" alt="screenshot 2018-02-15 13 49 31" src="https://user-images.githubusercontent.com/2288238/36238544-6639e05e-1257-11e8-8b71-9efae8d173fb.png">

**Comment by matthewberryman** [comment]
@LucieGueuning just noting that the screenshot has notifications going least recent -> most recent from top to bottom, but in cfbcef2 I changed that.

**Comment by LucieGueuning** [comment]
the most recent one need to be the first one (on top). thanks! 

All good otherwise.

**Comment by matthewberryman** [comment]
The most recent one is on top per https://github.com/MSFREACH/msf-reach/issues/251#issuecomment-365827604
