### ISSUE TITLE
add HOT OSM data as separate map layer for now

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#255]
cc @LucieGueuning

**Comment by matthewberryman** [comment]
@LucieGueuning I have this in but there are a lack of labels of what's what in the provided tiles. This is just a temporary stop gap. @talltom will email Mapbox to see what can be done there, otherwise we may have to look at writing extra software per https://github.com/MSFREACH/msf-reach-schema/issues/28
<img width="676" alt="screenshot 2018-02-15 13 49 31" src="https://user-images.githubusercontent.com/2288238/36289066-0242ecce-1312-11e8-9eaa-0019058241b0.png">

**Comment by matthewberryman** [comment]
(updated previous comment with correct screenshot, refresh page to pick it up if you can't see the map)

**Comment by LucieGueuning** [comment]
@talltom would it better to improve Humanitarian layer or mapbox functionality from your perspective?

**Comment by LucieGueuning** [comment]
Reopen, as I work on defining items on this layers of OSM

**Comment by matthewberryman** [comment]
I think the work @LucieGueuning is doing with HOT OSM https://github.com/hotosm/HDM-CartoCSS/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3ALucieGueuning will address this. Let's keep this issue open until those are satisfactorily closed.
