### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#263]
The notifications https://github.com/MSFREACH/msf-reach/issues/261 and tweets https://github.com/MSFREACH/msf-reach/issues/151 are being saved, it's just a caching issue that's stopping them showing up. I will try this out and then test on Chrome 64 on Windows 7.

**Comment by matthewberryman** [comment]
Tested it and was working fine for me. Will email Natasha and follow up.

**Comment by matthewberryman** [comment]
@LucieGueuning  I've not heard anything back from Natasha since changing this and informing of her via email. When did she report this: https://github.com/MSFREACH/IMPROVEMENT-FEEDBACK/issues/1#issuecomment-369679469 ?

**Comment by LucieGueuning** [comment]
Please see on each comments the time and date of reporting from Natasha

**Comment by matthewberryman** [comment]
confirmed by Natasha as resolved
