### ISSUE TITLE
VERY IMPORTANT Sub-tab to create below event tab (on landing page)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#268]
sub-tab to create: 
Monitoring & Assessment
Ongoing MSF projects

Event under 'Monitoring' and 'exploration' will be stored under the 'monitoring & assessment' tab. 
Event under 'Intervention (MSF activity)' will be stored under the 'Ongoing MSF Projects'

![image](https://user-images.githubusercontent.com/25951555/36797864-f8d57dd0-1ca0-11e8-9bdc-46df8fa498b8.png)

**Comment by matthewberryman** [comment]
We could make this two tabs fairly straightforwardly for part 1. Not sure about subtabs (@mehrdadgit ?)

**Comment by LucieGueuning** [comment]
@mehrdadgit possible to make as sub-tabs as per screenshot?

**Comment by mehrdadgit** [comment]
Hi @LucieGueuning @matthewberryman 

By sub-tabs you mean the way is currently done? 
Another option is pills: https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_pills_dynamic&stacked=h

**Comment by matthewberryman** [comment]
Issue superseded by https://github.com/MSFREACH/msf-reach/issues/372
