### ISSUE TITLE
Edit event need to be divided into two steps

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#269]
All fields from the left column (on the current view) expect SharePoint link ID need to be under the first tab 'Monitoring and Assessment'
All the other can be move the second tab 'MSF Activities (if any)'. Field can still be collapse and expandable to make in more user-friendly. 

![image](https://user-images.githubusercontent.com/25951555/36798397-6a47d886-1ca2-11e8-98de-b3f57575f19e.png)

It will be more compact and readable by the user.

**Comment by matthewberryman** [comment]
Decision made to drop modal in favour of in-line editing, and relevant sections for in-line editing now almost complete as part of #537
