### ISSUE TITLE
UI to be improved for scrolling down functions and map zoom in and out (on edit window on even page)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#270]
scrolling down functions and map zoom in and out are too close to each other. 

@talltom (specialist)
![image](https://user-images.githubusercontent.com/25951555/36799075-2ab436ea-1ca4-11e8-93a7-f1b67b8687fe.png)

**Comment by matthewberryman** [comment]
scrolling can be done in one of a number of ways (scroll bars, mouse wheel, trackpad, touch screen) that we can't control, if the maps are in the way (particularly an issue for touch screen where you need to touch somewhere off of the map to scroll) then they will be able to resized out of the way per https://github.com/MSFREACH/msf-reach/issues/274 plus the overall edit https://github.com/MSFREACH/msf-reach/issues/269 changes and other UX changes https://github.com/MSFREACH/msf-reach/issues/194 will cover this issue. Thus, closing this issue in favour of others that will deal with it.

**Comment by LucieGueuning** [comment]
Reopen as it is not solved for users. Only to keep track of that.

**Comment by mehrdadgit** [comment]
Hi @LucieGueuning @matthewberryman this is fixed now in this way for ALL maps: when you are on a mobile device, single-finger dragging/zooming is disabled ( you may still drag and zoom in/out with double finger gestures)  

Note, only for two Edit Event maps, Zoom-By-Scrolling is disabled on desktop too. Sing out if you need it disabled for other maps too.

**Comment by matthewberryman** [comment]
Event edit modal removed.
