### ISSUE TITLE
VERY IMPORTANT On legend, change 'current event' by 'Ongoing MSF Projects' on every map

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#273]

**Comment by matthewberryman** [comment]
This is now in the landing map in dev and will go into other maps as part of https://github.com/MSFREACH/msf-reach/issues/212#issuecomment-369324237

**Comment by LucieGueuning** [comment]
Reopen, as it is not done from user perspective

**Comment by matthewberryman** [comment]
The coding for this is done, making sure that code is used on other maps is part of a separate issue #212, let's keep this issue for the change itself (already done)
