### ISSUE TITLE
contact / social media trust algorithm to build

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#275]
- to cross-checked info
- to ensure people who tweet are most relevant than others (decision tree)
- to ensure that contact are trusted one (by looking at the relationship with this specific one).

**Comment by matthewberryman** [comment]
Not sure what you mean by "to cross-checked info"
As a simple approach for 2a part 1, for the twitter search result I can sort by (follower count / followee) if you like? Then we can discuss further based on feedback.

**Comment by matthewberryman** [comment]
Per my idea on the call, I am pretty sure I can tweak the search query to push this simple approach back onto Twitter's servers, and then just need to double check one other line in our code to make sure it's reflected in our list.

**Comment by matthewberryman** [comment]
@LucieGueuning that wasn't bringing up many tweets, so I reverted to the old way (which still gives some priority to tweets from more popular tweeters)

**Comment by matthewberryman** [comment]
Using Twitter's algorithms on this.
