### ISSUE TITLE
per operator restriction of RSS feeds

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#277]
depends on https://github.com/MSFREACH/msf-reach/issues/57

**Comment by LucieGueuning** [comment]
With AD, we will attribute location preferences for people who are monitoring America for example.

**Comment by matthewberryman** [comment]
1. Operators can turn on / off individual RSS feeds (saved in cookies), and
2. We've decided to restrict geographically per #357 
so I don't think this is needed any more?
@LucieGueuning

**Comment by LucieGueuning** [comment]
close it if ok for you.

**Comment by matthewberryman** [comment]
Part 2a: table in line with saved layer selection.
Part 2b: 
* other RSS feeds in other regions
* develop and promote standard

**Comment by matthewberryman** [comment]
other ones #416 and #417

Table in line with saved layers is now part done in dev/test: on landing page load the table will line up with saved setting. Making it dynamic I will do tomorrow.
