### ISSUE TITLE
VERY IMPORTANTCountry undefined on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#280]

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/36844732-cc17619a-1d4b-11e8-9c1b-1cffa11e2a50.png)

Why is it undefined as we have epicenter on map. Should recognize

**Comment by matthewberryman** [comment]
@LucieGueuning This is working in dev; it's not showing in prod as I haven't configured prod yet as I am awaiting a response from you on https://github.com/MSFREACH/msf-reach/issues/195#issuecomment-365815489

**Comment by matthewberryman** [comment]
Just to be clear, I've had the code deployed to prod (I'm not that behind on merges), just need to flick the configuration switch.
