### ISSUE TITLE
Type of event on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#281]
should be appearing as inputting when creation of event. e.g. earthquake and not 'natural_hazard' each time. 

Also, you can remove sub-type as we have the field type up on meta-data. it is duplication no? 
![image](https://user-images.githubusercontent.com/25951555/36844817-1b600cde-1d4c-11e8-9111-554f3f667fcd.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/37784479-cf324138-2def-11e8-982a-bd453170b1bc.png)

Country broken? 
Type, why do we have a ',' before the word earthquake?

**Comment by matthewberryman** [comment]
* Country is (1) not part of this issue, (2) happening because I need to re-run the geocoder for old events (before we turned on the automatic geocoding on prod platform), https://github.com/MSFREACH/msf-reach-schema/issues/39
* Missing comma fixed with commit 5de11df

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/40239707-b1ab97c2-5aae-11e8-8a17-55ea2aa9e05c.png)
Can we put a capital letter to Displacement when display (to check if other are well spelt) + remove coma?

**Comment by matthewberryman** [comment]
Just noting that making the first letter a capital, which is what I think you mean, is a point of grammar, not spelling.
