### ISSUE TITLE
Incorporate API from health sites on REACH (Humanitarian Layers)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#282]

**Comment by matthewberryman** [comment]
a little buggy:
* sometimes sites vanish as you zoom, 
* or are slow to load on initial map load, and 
* clusters particularly map icons need work

but there's a start on this on the landing page. cc @LucieGueuning

**Comment by matthewberryman** [comment]
(just on dev / test environments for now while I continue work on this)

**Comment by LucieGueuning** [comment]
If it is too much work, or not useful, please ignore this (part of your judgement).
