### ISSUE TITLE
Total population/population affected on prod side

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#284]
To remove if no number filled on prod side. 

**It is perfect on dev side**. (BTW, should I give feedback on which one? the dev side right?) Could you please merge all the changes soon? Thanks!

![image](https://user-images.githubusercontent.com/25951555/36855450-656ee51a-1d6b-11e8-82ed-dee67cdb0bec.png)

**Comment by matthewberryman** [comment]
Yes please give feedback based on dev, which is the most up-to-date. I will be doing another merge on Sunday and trying to merge at least once / day—I am a little behind as I was focussing on fixing a lot of issues first on Wednesday-Friday for your review, and then I will review this weekend.

**Comment by matthewberryman** [comment]
Now merged into prod and working.
