### ISSUE TITLE
VERY IMPORTANT session to re-structure

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#286]
![image](https://user-images.githubusercontent.com/25951555/36855769-4abff0fa-1d6c-11e8-8161-e082ae31532a.png)

to be as below: 
![image](https://user-images.githubusercontent.com/25951555/36856006-dd7011b4-1d6c-11e8-88e3-e74b2061a4ed.png)

Under About, we will put the two videos, the link to SharePoint, a brief description and the partnership and confidentiality file. 
Under FAQ, we will integrate all the questions and answer that @anexact and myself will provide.

**Comment by LucieGueuning** [comment]
need to have the possibility to sign out.

**Comment by matthewberryman** [comment]
Adding signout functionality requires substantial changes from database to server (since we cannot track this within the web server itself as we allow for more than one due to platform availability and performance reasons). Also noting that adding it will also sign you out of /all/ MSF apps. Still want to add it in?

**Comment by LucieGueuning** [comment]
Yes, confirmed, still want to do it. Thanks.

Lucie Gueuning
REACH Project Manager, Emergency Response Support Unit
Médecins Sans Frontières - Hong Kong | 無國界醫生(香港)
Phone: +44<tel:+852%206279%207636> 7423 392179
Email: lucie.gueuning@hongkong.msf.org<mailto:lucie.gueuning@hongkong.msf.org>
Skype: lucie.gueuning
_______________
Please visit MSF REACH Project Deployment<https://msfintl.sharepoint.com/sites/hk/projects/MSF-REACH/SitePages/Home.aspx>

On 14 Mar 2018, at 11:43 PM, Matthew Berryman <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding signout functionality requires substantial changes from database to server (since we cannot track this within the web server itself as we allow for more than one due to platform availability and performance reasons). Also noting that adding it will also sign you out of /all/ MSF apps. Still want to add it in?

**Comment by anexact** [comment]
@LucieGueuning @matthewberryman I would reconsider bx if it logs people out of their email at the same time, this could be perceived as a bad glitch! I think given that problem, we should not make the button at this point. Better to have it on and working than shutting MSF people out of their whole system for now, no?

**Comment by LucieGueuning** [comment]
Let raise this small question at the meeting on Monday.

**Comment by anexact** [comment]
<img width="1199" alt="screen shot 2018-03-18 at 8 37 58 am" src="https://user-images.githubusercontent.com/20785542/37563755-32f56954-2a88-11e8-9858-8160cb763d72.png">

Depending on how @matthewberryman wants to deal with the pop up for the login, I would stay with something really simple until end of Phase 2, but we can make additional prototypes w/ Wolfgang for @LucieGueuning to continue to review depending on how minimalist we want to go — but he and his wife had a baby on Thursday, so maybe hear from him next week :-)

<img width="398" alt="screen shot 2018-03-14 at 8 54 48 am" src="https://user-images.githubusercontent.com/20785542/37563760-521c97b2-2a88-11e8-840d-af6c8b9d99a1.png">

**Comment by matthewberryman** [comment]
Thanks. This one also requires some server rework in light of AD integration #57.

If you can get a draft of FAQ to me ASAP though there’s already a place for that in the menu.

Sent from my iPhone

On 18 Mar 2018, at 18:45, Etienne Turpin <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2018-03-18 at 8 37 58 am]<https://user-images.githubusercontent.com/20785542/37563755-32f56954-2a88-11e8-9858-8160cb763d72.png>

Depending on how @matthewberryman<https://github.com/matthewberryman> wants to deal with the pop up for the login, I would stay with something really simple until end of Phase 2, but we can make additional prototypes w/ Wolfgang for @LucieGueuning<https://github.com/luciegueuning> to continue to review depending on how minimalist we want to go — but he and his wife had a baby on Thursday, so maybe hear from him next week :-)

[screen shot 2018-03-14 at 8 54 48 am][37563760-521c97b2-2a88-11e8-840d-af6c8b9d99a1.png]<https://user-images.githubusercontent.com/20785542/37563760-521c97b2-2a88-11e8-840d-af6c8b9d99a1.png>

**Comment by anexact** [comment]
In the Google Drive:
https://docs.google.com/document/d/1EOUMOqX1iz7daWXD5hswrqgueiTtK3ldTmGLkEnCupI/edit?usp=sharing

**Comment by LucieGueuning** [comment]
- Go for the suggestion of Etienne for Log in page please 
- Go for a logout button even it is logging out from all other apps of Office 365. It is how it works for every single apps linked to the AD. We are used to it. And I want a logout button. Thanks!

**Comment by matthewberryman** [comment]
Noted

**Comment by LucieGueuning** [comment]
input from me?

**Comment by matthewberryman** [comment]
Not required @LucieGueuning . The bulk of this work is done. I want to put in the login page but last I had a look it was quite tricky to get the workflow happening with respect to our existing workflow (before AD integration) + AD integration on top of that + combined with some of the error reporting around our API.

**Comment by LucieGueuning** [comment]
- Please correct with 'Sign out' (and not logout) 
- Please correct with 'About MSF REACH' 9and not About MSF -REACH

Thanks

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/40239464-0ecb074a-5aae-11e8-8175-533f1095c77a.png)
Why on event page, the username becomes 'session'?
