### ISSUE TITLE
Search box for table (contacts, missions, etc.) and search box for location (validated by Google Map) on every map on REACH

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#292]

**Comment by matthewberryman** [comment]
@LucieGueuning @anexact On the landing page there's no table by which to display contacts. I would argue against this as the UI is getting cluttered, and from a UX perspective it makes sense to do this on a per event basis (hence events page only).

@talltom can you please have a look at refactoring the google autocomplete function so we can attach it to multiple maps on the page. If you run out of time on the weekend then sing out and in that case @mehrdadgit can take a look early next tweek.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/37787042-0421f4dc-2df6-11e8-80f2-fc9cce1c5ed1.png)

as per contract

**Comment by matthewberryman** [comment]
Done bar event geoselection which is not part of this issue but part of https://github.com/MSFREACH/msf-reach/issues/209
