### ISSUE TITLE
On event page, add one tab with Ongoing MSF Projects/Missions

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#293]
As we will have the Ongoing MSF Projects on the map (as per #288)

On event page, add one tab with the table 'Ongoing MSF Projects/Missions' of the whole country where the event is happening (even thought it is not close to it). 

e.g: event in Bali, should have under this tab 'Ongoing MSF Projects', the project in Jakarta and others in Indonesia (ongoing MSF Activities).

**Comment by matthewberryman** [comment]
@LucieGueuning this depends on geocoding so needs your response on the other thread.
@talltom the API will need an update to search by event metadata.country

**Comment by LucieGueuning** [comment]
response send (ok but need to share that with sponsors)

**Comment by matthewberryman** [comment]
@mehrdadgit can you please sometime today (in events.js) do the linking between table and popups, the same as for contacts and missions.

**Comment by LucieGueuning** [comment]
Can you add, as asked, /Missions to the tab name?

**Comment by matthewberryman** [comment]
Wouldn't that be tautological? Adding it would (in a negative way) affect the layout of the tabs as well as the map layer selection box.

**Comment by LucieGueuning** [comment]
So we need to find another solution in term of UI/UX, but for MSF'ers it is a must in term of coherence.

**Comment by LucieGueuning** [comment]
'Ongoing MSF Responses' is alright
