### ISSUE TITLE
Editing of field on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#301]
New ideas: more straight forward for users. 

Having for each tab collapse on event page, a button to edit specifically the field. Cf. picture below
![image](https://user-images.githubusercontent.com/25951555/36860557-7d242586-1d79-11e8-8049-a8efbba1cfac.png)

And it will solve a lot of issue of the edition part (popup window)

**Comment by mehrdadgit** [comment]
I guess this is done @matthewberryman ?

**Comment by matthewberryman** [comment]
No, what @LucieGueuning means is to have editing on the page rather than edit button opening a section of a modal. See https://github.com/MSFREACH/msf-reach/issues/363 for more details. Closing this issue as it's a dupe of #363.
