### ISSUE TITLE
VERY IMPORTANT input coordinates when creating event

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#302]
Comment from Natasha: I tried to input coordinates when determining the location of an event, but it wouldn’t work.  That would be useful for earthquakes, because they happen in a specific area.

**Comment by matthewberryman** [comment]
@mehrdadgit I had a look at the Google Autocomplete box and API and it doesn't support entry of lat-lon so you will need to add an extra box for this.

**Comment by mehrdadgit** [comment]
Done @matthewberryman just note that on event edit popup, (only in case of msf response where the user is allowed to change the location, the user needs to specifically click on the map to add the pin and actually change the location)

**Comment by matthewberryman** [comment]
can you please fix the zoom level? It starts zoomed in as close as possible. Please adjust to ~ country scale level of zoom.

**Comment by mehrdadgit** [comment]
You mean when enter values to ‘locate by coordinates’ and click the find button ? If so, what zoom level you suggest?

**Comment by mehrdadgit** [comment]
Cause i tought locating by coordinates is a very specific location that the user may need to verify with the highest zoom level ...

**Comment by matthewberryman** [comment]
No, at highest zoom level you can't see anything (RSS hazards, contacts, etc.) around it (I suppose if you're interested in verifying by streets but in that case you'd be using the street search).

Try zoom level 5.
