### ISSUE TITLE
lost info on TS Sanba

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#308]
! I clicked on the typhoon Sanba page and it looks like all the info is missing.  I’m on my Mac using google chrome.  The screenshot is attached.  I’ve already closed the event.

Time of reporting: Tue 06/03/2018 19:18

![image](https://user-images.githubusercontent.com/25951555/37053466-2542a99c-2174-11e8-83fd-d17db68852d6.png)

**Comment by matthewberryman** [comment]
Was this before or after you closed it?
What is the event ID # from the URL? If it’s closed then it’s much easier for me to work from this than dig it up from the database especially as I’m on the road today.

Sent from my iPhone

On 7 Mar 2018, at 06:26, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


! I clicked on the typhoon Sanba page and it looks like all the info is missing. I’m on my Mac using google chrome. The screenshot is attached. I’ve already closed the event.

[image]<https://user-images.githubusercontent.com/25951555/37053466-2542a99c-2174-11e8-83fd-d17db68852d6.png>

**Comment by matthewberryman** [comment]
"The same problem popped up after I edited the PNG earthquake event, even when I clicked on the event tab.  But the updated info came out when I exited then re-entered the event. "

I think it may be related to #307 - I am just about to deploy a fix for that to dev and will know soon.

**Comment by matthewberryman** [comment]
Tested latest work on dev and seems fine, will retest tomorrow and then test again once this is in prod.

**Comment by LucieGueuning** [comment]
FYI, sent by Natasha on Tue 06/03/2018 20:33 : I have encountered the same issue for the PNG earthquale.  Event ID is 40.  Then I was signed out (automatically by the platform), and when I signed in again, the info reappeared.  So I guess the info isn’t really lost.  Will let you know if I encounter the problem again.

**Comment by matthewberryman** [comment]
I've not heard anything back, closing this.
