### ISSUE TITLE
event tab as default and not mission tab (when opening an event)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#309]
I noticed that opening the event page, it looks like we’re on the missions tab, when we’re actually on the event tab.

Time of reporting: Tue 06/03/2018 19:23

![image](https://user-images.githubusercontent.com/25951555/37053615-849675d6-2174-11e8-8122-41e889562245.png)

**Comment by matthewberryman** [comment]
Duplicate of #307

Sent from my iPhone

On 7 Mar 2018, at 06:32, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


I noticed that opening the event page, it looks like we’re on the missions tab, when we’re actually on the event tab.

Time of reporting: Tue 06/03/2018 19:23
