### ISSUE TITLE
pre-fill and pre-load Twitter search

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#32]
take event name and summary words from events API and pre-fill Twitter search keywords on events page, and run search automatically on those, allowing user to modify and re-run search

**Comment by matthewberryman** [comment]
@talltom thanks for work so far, but given type is fairly broad when compared with terms used by twitter users for specific events, that's not returning much as we discussed, so leave off type, and just OR the name together and also optionally (by putting in code but commenting out for now, so I can easily add in later if need be) the ORing of the event summary words also.

**Comment by matthewberryman** [comment]
Done in https://github.com/usergroupcoop/msf-reach/commit/ee0f9a74054fb390d8e64ff4331f58b0d8358167 
cc @LucieGueuning we played around with various ways of doing this and this seemed the best. I will raise a separate issue for translation later.

**Comment by matthewberryman** [comment]
double check on this in relation to different forms of event names
cc @LucieGueuning

**Comment by LucieGueuning** [comment]
twitter still not linked to location of event, right?

**Comment by matthewberryman** [comment]
No - it's based on whatever is in the event name, which by default does not contain the location, although you could edit it to include it. There are a number of options (some paid, some with privacy implications) that we will need to explore in phase 2 for this.

**Comment by LucieGueuning** [comment]
OK, need to improve twitter search anyway and this is part of the Phase 2.

**Comment by matthewberryman** [comment]
To explore:
* Language translation linked to geolocation.
* Putting in some semantic awareness (even just picking more common synonym).
* Other AI possibilities.

**Comment by LucieGueuning** [comment]
location if possibility to have a deal with Twitter for advanced search

**Comment by matthewberryman** [comment]
@LucieGueuning  my comments are also relevant here

> Some thoughts and progress on twitter search:
> 
> I think the best search search terms to use are:
> Type or subtype (but not both)
> Country*
> Possibly the year?
> 
> Here I mean as a keyword not as a location (bounding box) filter which will not work reliably because of Twitter UX issues.
> I have some changes in the dev environment just going live now (after local testing) to geocode location of the event on the map to country, and include that in the metadata, used in Twitter search as per above. Important notes:
> •	This only applies on creation of new events. I need to separately work on code for updated events, and old events already in the system.
> •	I am using Google geocoding with an API key I have, so do not put any sensitive location information into the dev environment until we’ve had a discussion around privacy issues and also the amount we want to put through (there’s a fairly generous free limit but still…)
> •	There is still some UI work to display the country information elsewhere in the system
> 
> This test event in the dev environment, local to me, had Australia automatically added as the country, and that shows a fairly decent twitter search results by default:
> https://dev.msf-reach.org/events/?eventId=32

**Comment by matthewberryman** [comment]
pre-filled using event name (now user specified and can be edited on event and further refined on twitter search page field) and pre-loaded

**Comment by LucieGueuning** [comment]
To explore:

Language translation linked to geolocation.
Use of RSS feed (for events created from RSS #180 )
Putting in some semantic awareness (even just picking more common synonym).
Other AI possibilities.
location if possibility to have a deal with Twitter for advanced search

**Comment by matthewberryman** [comment]
Language translation is now done (possibly has a few bugs around missing translations but generally seems to work). It's impossible to automatically translate based on country as some countries have more than one language but I will work on a recommendation system tomorrow based on country.

**Comment by LucieGueuning** [comment]
Great! To be presented to the sponsors on 19th of March (as a great asset)

**Comment by LucieGueuning** [comment]
To explore: Others things not finished right?

Language translation linked to geolocation.
Use of RSS feed (for events created from RSS #180 )
Putting in some semantic awareness (even just picking more common synonym).
Other AI possibilities.

**Comment by matthewberryman** [comment]
"Language translation linked to geolocation." <- functionality is done but I need to enable geolocation for prod, and there are a couple of SE Asian countries missing from my list that I need to add.
Event creation from RSS feed icons / anything else of note on the map is done per comments I made on #180 

Other times not done.

**Comment by matthewberryman** [comment]
sorry, just to clarify, although in #180 you can create an event from an RSS point on a map it doesn't (yet) use the information for Twitter search. Sorry, I read this in too much of a hurry yesterday. On language from geolocation, I am just about to put some commits in to wrap this up: I was missing a couple of official languages for SG, and I will put a notice on the site that event lat,lng coords are geocoded.

**Comment by LucieGueuning** [comment]
Bug reported from Natasha (Sun 18/03/2018 17:10):
•	I checked the twitter feed for the PNG earthquake and nothing was showing.  There are lots of tweets if you go on the Twitter site.

**Comment by matthewberryman** [comment]
@LucieGueuning see #330 for that issue, I will re-open that if Natasha confirms in negative on email that it's not working for her.
