### ISSUE TITLE
General report from peers (not linked to specific event)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#334]
I would like to thanks our contacts for filling out our google form or contact card and let them know how they can report something happening in their area of living. FYI, they are not MSF staff, they are public. This will help to have more report card sent to event and will be more interactive for our super momentum. 

I need to wait for us to find a solution of having a general link for report, not linked to a specific event. Do you have any smart idea? Tom or Etienne can maybe help out on that? 

Thanks.

**Comment by LucieGueuning** [comment]
SOLUTION: 
- Add a tab on landing page, on the right, next to 'Contact', called 'Reports'
- Having a general URL for report not asked through a specific link that peers can bookmarks on their browser
- Having the general report stored into this tab with an additional features, which is a dropdown on the right with the possibility for operators to allocate the report to a specific 'ongoing event'. dropdown menu needs to contain all the 'ongoing event'.

**Comment by matthewberryman** [comment]
@talltom can you please work on schema and API changes
@mehrdadgit can you then please work on UI changes

**Comment by matthewberryman** [comment]
@mehrdadgit I've been busy on schema and API and UX work. I have sent you a dump of my local msf_reach database that has the schema changes plus a couple of reports in (one unassigned to an event) for testing. 
I need your help to resolve some issues with recent commits in the event_free_reports branch:
* Tab content for reports -> unassigned reports showing up down the bottom.
* Is it possible to default to selecting unassigned reports (and corresponding tab content display) by default on reports top level tab open?

**Comment by mehrdadgit** [comment]
First point should be solved @matthewberryman 
I will have a look at second issue this evening; there is also a UI bug that if you switch between top level tabs a couple of times the contents of bottom level tabs hide out.. I will try to fix both  this evening.

**Comment by matthewberryman** [comment]
ok thanks, even that much for now helps me with further testing of more features I'm going to add.

**Comment by mehrdadgit** [comment]
@matthewberryman I suspected some js code is interfering with tab selection, I removed it and it seems to be fixed now :)

**Comment by matthewberryman** [comment]
I can now create reports under /reports/ (not linked to event); on the todo list:
* More testing
* Resolve #401 (possibly part of this).
* On assignment, remove the item from the table dynamically and also make sure map is updated.

**Comment by matthewberryman** [comment]
@LucieGueuning this is done though I would like Mehrdad and Tom to review some of the code first as it's a pretty major change on a number of fronts from database to API to even some of the build parameters.

**Comment by matthewberryman** [comment]
@LucieGueuning This is now deployed to dev and test environments - please try it out and let me know what you think.

**Comment by matthewberryman** [comment]
@LucieGueuning just noting that unassigned reports show up on the map and table on the landing page until either ignored or assigned to a new or existing event.
