### ISSUE TITLE
Map search on landing page not working anymore

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#344]
![image](https://user-images.githubusercontent.com/25951555/37784177-1600ebba-2def-11e8-8afe-7e505b4a5128.png)

**Comment by matthewberryman** [comment]
should be fixed in next five minutes, please test and close off if working, @LucieGueuning

**Comment by matthewberryman** [comment]
tested on dev and working, also reviewed API key settings and they seem OK for prod too. closing
