### ISSUE TITLE
Contacts, missions gathered under number (according to zoom out and in)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#354]
![image](https://user-images.githubusercontent.com/25951555/38313431-ec63c1a6-381b-11e8-899e-209b64d83ddb.png)

**Comment by matthewberryman** [comment]
duplicate of https://github.com/MSFREACH/msf-reach/issues/339

**Comment by matthewberryman** [comment]
Per discussions today seems changes to respond to [previous comment](https://github.com/MSFREACH/msf-reach/issues/354#issuecomment-379822847) have gone in the wrong direction.
