### ISSUE TITLE
default map layers

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#355]
@anexact writes: 
"Upon login as tomas@, the default icons should be:
Ongoing MSF Projects
& RSS Feeds
(not Mission Histories)"

I am not sure if https://github.com/MSFREACH/msf-reach/issues/172 addresses this issue? If we want to have a particular set of defaults for first login then I think that should be based on what would work best for the majority of people.

**Comment by anexact** [comment]
In meeting with @LucieGueuning, we reviewed the UX from POV of new users to the platform and felt that the Mission Histories should be default Off, while Ongoing MSF Projects & RSS Feeds should be on. However, I will start another thread re: Right Side Tab and Sub-Tabs that resulted from that meeting.

**Comment by matthewberryman** [comment]
Got this in. I would argue we probably want contacts (at least non-MSF ones) off by default? Maybe healthsites off too? @anexact @LucieGueuning 

Starting a new incognito session should start with a fresh set of cookies although unless you close and re-open chrome it seems to keep them across incognito sessions even. To clear, turn on dev tools, go into application, and find the cookies for the site you're on and right/command click and select clear:
<img width="520" alt="screenshot 2018-04-18 14 39 22" src="https://user-images.githubusercontent.com/2288238/38915617-eaf5f392-4316-11e8-89e2-317e49221a9b.png">

<img width="400" alt="screenshot 2018-04-18 14 39 42" src="https://user-images.githubusercontent.com/2288238/38915622-f14ba958-4316-11e8-9de2-01488aa5f855.png">

<img width="293" alt="screenshot 2018-04-18 14 40 14" src="https://user-images.githubusercontent.com/2288238/38915628-f645da50-4316-11e8-9d45-46d677fb9c23.png">

**Comment by LucieGueuning** [comment]
Off for non-MSF contacts and off for healthsites (as default), I confirm! :)
