### ISSUE TITLE
support editing of original location with geocoding of country

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#356]

**Comment by matthewberryman** [comment]
Checking database, the location entered was https://goo.gl/maps/abS4tRnVAm42 which is near to Langkawi but in Thai waters.

**Comment by matthewberryman** [comment]
Per whatsapp from @LucieGueuning  have updated the metadata for this (despite co-ordinates being in Thailand).

**Comment by LucieGueuning** [comment]
Cannot update co-ordinates on REACH

**Comment by matthewberryman** [comment]
Users can now double click on the event map in the edit modal and it will adjust the location and update the country
