### ISSUE TITLE
UI for SE Asia

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#357]
@anexact writes:
"Upon login as tomas@, the map is not centered on SEA.
We need to make the map SEA-focused, and find a design UI solution to EXPLICITLY say it is only for Southeast Asia (solution could be like PB.id)."

I have changed the centering (now in dev) per https://github.com/MSFREACH/msf-reach/issues/141

If you want to commit to forcing it like in PB.id I can borrow that code.

**Comment by anexact** [comment]
I think we should commit to forcing it as in PB.id to prevent non-ERSU users from trying to move outside the SEA bounding box and then believing it is broken elsewhere. @LucieGueuning do you agree on this?

**Comment by LucieGueuning** [comment]
agree

**Comment by matthewberryman** [comment]
@LucieGueuning @anexact please test in our dev environment

**Comment by matthewberryman** [comment]
There's a known bug in our platform (dev for now) in that popups can display outside of the maxbounds and these are temporarily shown in full before the map snaps back to the maxbounds I've set. This is caused by a known bug in leaflet https://github.com/Leaflet/Leaflet/issues/2324 and the RRose plugin provides a solution. I probably won't get time to look at this until early tomorrow Chinese time. Anything else, sing out.

**Comment by LucieGueuning** [comment]
well noted. I guess it is the same issue that #376

**Comment by LucieGueuning** [comment]
Need to have access to the Nauru island for project just opened by MSF

**Comment by matthewberryman** [comment]
#376 was a separate issue. 

@LucieGueuning can you please send me a complete list of countries that you want included as Nauru for example is not normally considered part of SE Asia.

**Comment by matthewberryman** [comment]
@LucieGueuning reminder I am awaiting your feedback on this too.

**Comment by LucieGueuning** [comment]
Sorry for delay: 
countries that needs to be covered at least: 
- Bangladesh
- Cambodia
- China
- India
- Indonesia
- Malaysia
- Myanmar
- Nauru
- Nepal
- PNG
- Thailand
- The Philippines
- Vietnam

it is where we consider the SEA mission for MSF (5 OC's). Linked created on SharePoint for each of them already. 

Thanks

**Comment by matthewberryman** [comment]
Ok. These additional countries outside of the usual geographical definition of SE Asia (see https://asiasociety.org/education/introduction-southeast-asia , http://www.newworldencyclopedia.org/entry/Southeast_Asia ) will be added by the next deadline due to the delay in getting this changed requirement.

**Comment by matthewberryman** [comment]
Just noting that while I originally centre and bound the map on SE Asia, I've needed to relax the strict snapping back to the region, in order to accommodate the way the plugin used for #433 works. Also noting #455

**Comment by matthewberryman** [comment]
Default view on first login is open to whole of world map and then map extents are saved for users after that.
