### ISSUE TITLE
Request to compress the data displayed in the Event details 

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#362]
<img width="723" alt="screen shot 2018-04-04 at 4 51 29 pm" src="https://user-images.githubusercontent.com/20785542/38473609-f6dd5ff0-3b92-11e8-9506-53f24be35ea2.png">
@LucieGueuning suggested in our UX review that this information could be further compressed to be less dominant on the Event page and thus avoid hiding the Edit buttons below. If possible, can we try a much more compressed view of these details?

**Comment by matthewberryman** [comment]
I think we can drop creator and edits down to other sections. Same with sharepoint link? 
@LucieGueuning @anexact please provide a revised list.

**Comment by LucieGueuning** [comment]
creator and edits can be remove from this list and add description

**Comment by matthewberryman** [comment]
@LucieGueuning I have removed creator and edits (on dev for now until I merge) - what you do you mean by "description" though as there's no generic "description" field but rather ones like description of severity (which we already have), security, population, results of explo mission ?

**Comment by LucieGueuning** [comment]
There is no generic 'description' field so it is the reason we need to add one. Can it be on the event creation field to be completed at that time?

**Comment by LucieGueuning** [comment]
right before 'latest notification' field

**Comment by matthewberryman** [comment]
closing this as done bar description now opened in new issue https://github.com/MSFREACH/msf-reach/issues/435
