### ISSUE TITLE
Request to make Event Edit feature open inside tab not pop up

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#363]
Currently, Edit buttons open pop up, but can they instead expand that tab, with an option to again collapse the tab at the bottom. UX and data entry improvement if they can all open and close more smoothly. @LucieGueuning hope I got this one correctly, but add further explanation if not clear.
<img width="709" alt="screen shot 2018-04-04 at 4 50 44 pm" src="https://user-images.githubusercontent.com/20785542/38473643-ac0f46a4-3b93-11e8-9e07-17992499e97f.png">

**Comment by matthewberryman** [comment]
@mehrdadgit please work on this after your contact edit/deletion work

**Comment by LucieGueuning** [comment]
design need to be obvious for people to edit field.

**Comment by qclin** [comment]
@matthewberryman  can closed this with the work done in #579
