### ISSUE TITLE
Request to alter text in the Create New Event field

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#364]
Request from MSF to remove the phase: "Add event metadata" 
<img width="1196" alt="metadata remove" src="https://user-images.githubusercontent.com/20785542/38473787-b3c38746-3b95-11e8-9831-4ab49d2e1c29.png">

**Comment by matthewberryman** [comment]
Dupe of https://github.com/MSFREACH/msf-reach/issues/358
