### ISSUE TITLE
notification box + overview box on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#367]
for each event, we should have a notification box (which is now working really well), and an overview box.  The overview box can give a general description of the event, and should be on top of the notification box. 

@anexact what do you think? It can help the user on event page right?

**Comment by matthewberryman** [comment]
We already have a set of existing fields that start to provide a overview already (perhaps with some additions see https://github.com/MSFREACH/msf-reach/issues/362 )  ?

**Comment by LucieGueuning** [comment]
yes covered by #362
