### ISSUE TITLE
Vizalytics work 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#370]
- integration of API
- test of API
- Good display on REACH of info (numerical, sentences, tables, geo JSON)

**Comment by matthewberryman** [comment]
@mehrdadgit 
* API (mock output for now): https://msf-api.vizalytics.com/event - requires headers `Content-Type: application/json` (of course) and `x-api-key: API-key-I-will-share-with-you-in-LP`.
* API definition: [json](https://github.com/MSFREACH/msf-reach/blob/dev/ai/swagger.json), [yaml](https://github.com/MSFREACH/msf-reach/blob/dev/ai/swagger.yaml) that you can run through https://editor.swagger.io/ for pretty display.
* Example [request body](https://github.com/MSFREACH/msf-reach/blob/dev/ai/example_post_body.json) (Note: I will commit soon to update capacity and deployment details but neither here nor there for now).
* Example [response](https://github.com/MSFREACH/msf-reach/blob/dev/ai/example_response.json).

Response is a JSON object with two fields:
status: did it work, if not, a message, plus a uuid, mostly so we can debug, log, etc.
results: 
a list of Result objects. Assume it's an ordered list, in relevance ranking order.  A result object will have a 'topic' key plus one or more of:
insights: 
a list of sentences
geo:
a GeoJSON FeatureCollection - assume that you can then use Leaflet's FeatureCollection layer to display in one shot.
data:
a generic JSON object in the spec, but assume it's one or more keys each with a value that is a mixed multidimensional array holding tabular data.

Can you please work on a modal in a separate .html file now (that we can transclude later as I haven't quite figured out where to put it) + js code for fetching from the API given event details and taking the AI response and display it (you will need a map).

**Comment by mehrdadgit** [comment]
OK. confirming first we need to interface this with the reach API to avoid CORS limitations?

**Comment by matthewberryman** [comment]
Yes and also to ensure only authenticated users can call it (and keeping the API key secret in env vars).

Sent from my iPhone

On 21 Apr 2018, at 20:26, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. confirming first we need to interface this with the reach API to avoid CORS limitations?

**Comment by matthewberryman** [comment]
@luciegueuning please put any AI UI designs here

**Comment by LucieGueuning** [comment]
AI and ML - UI to have after hitting 'creation button' - pop up window
![image](https://user-images.githubusercontent.com/25951555/39225212-e574a900-4842-11e8-8abc-a8cd936a2a53.png)

**Comment by mehrdadgit** [comment]
Done @matthewberryman  have a look at PR; For now it shows this modal after submission: 
![image](https://user-images.githubusercontent.com/7603978/39237428-d5dace26-48be-11e8-9d59-ab5a5621ddcf.png)

Change wording as necessary.

**Comment by matthewberryman** [comment]
@LucieGueuning This is now deploying into our dev & test environments.
@mehrdadgit on my screen the modal is too large and I struggle to make the window big enough to click on the "done" button - can you please fix (in dev branch)

<img width="889" alt="screenshot 2018-04-25 20 25 42" src="https://user-images.githubusercontent.com/2288238/39245867-7c7ecd10-48c7-11e8-9629-abae653e093d.png">

**Comment by matthewberryman** [comment]
@mehrdadgit can you please fix asap. Demo session is tomorrow afternoon Jakarta time.

**Comment by mehrdadgit** [comment]
Have put a fix on dev @matthewberryman

**Comment by LucieGueuning** [comment]
BUG: no results coming. 

When are we migrating the first version of this on prod?

**Comment by LucieGueuning** [comment]
ML working on profile/search like Google/Facebook ads. based on your credential, specifically.

**Comment by matthewberryman** [comment]
This is already on prod. I will flag no results issue with Vizalytics. ML on profiles covered in https://github.com/MSFREACH/msf-reach/issues/452 awaiting feedback on that.

**Comment by matthewberryman** [comment]
Results seem ok now. Have followed up with Vizalytics to check on that transient issue.

**Comment by LucieGueuning** [comment]
Machine to learn: cg. email sent to Chris

**Comment by matthewberryman** [comment]
Confirmed that vizalytics is picking up MH data. Remaining UI work covered by #537
