### ISSUE TITLE
logo on landing page needs to be bigger by 2 times

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#371]

**Comment by matthewberryman** [comment]
making the logo double the size means I have to make the row it's in double the size, so it ends up being (on my screen) going from around 6.75% of the size to around 13.5% of the total height, leaving significantly less room for the map. The main issue with the icon as I see it is that the text for MSF is too small, so is there an alternate icon I could use that doesn't have that text, or has it bigger?

**Comment by anexact** [comment]
I agree, it cannot be double the size or the row is completely out of scale. @LucieGueuning can you review other MSF logo options re: non-text-based logo that might work better?

**Comment by LucieGueuning** [comment]
Please see all the options here: https://drive.google.com/drive/u/0/folders/0Bw27FPU-gFxYQnlvU1VETHJvZUE

**Comment by LucieGueuning** [comment]
need input from me?

**Comment by matthewberryman** [comment]
we're already using the one with least amount of text and biggest font so short of MSF going back to drawing board there's not much we can do

**Comment by matthewberryman** [comment]
No longer relevant; this is for dev site only and test/prod have latest logo as completed in #596
