### ISSUE TITLE
Organization of "Event" top nav tabs

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#372]
<img width="1154" alt="screen shot 2018-04-10 at 3 28 32 pm" src="https://user-images.githubusercontent.com/20785542/38559579-af6953a8-3cd3-11e8-8d08-906b915eafe1.png">
( @matthewberryman as I mentioned, there are several items for reorganization after the UX meeting with @LucieGueuning ... this is 1/3)

Can we reorganize the tabs into 2 distinct sets:
Upper Set (Main): Status / Contact
Lower Set: [ Status] Monitoring & Assessment / Ongoing Projects / Mission Histories / RSS Feeds
Lower Set: [Contacts] Contacts / Add a Contact / Search

@LucieGueuning please confirm?

**Comment by anexact** [comment]
<img width="468" alt="tab nav" src="https://user-images.githubusercontent.com/20785542/38559766-2b3e8868-3cd4-11e8-9f01-c88dd930dee3.png">
Currently, we have this; UX not working well, above is just sketch, but the content is correct unless @LucieGueuning wants it changed, but we will confirm in meeting today 16h00 CET.

**Comment by LucieGueuning** [comment]
GOOD!

I would put 'Event Status' instead of 'Status', no?

**Comment by anexact** [comment]
Yes.

**Comment by matthewberryman** [comment]
I'll have a go at this but my concern is that it will end up taking a bit too much space on the RHS so if you have any other ideas @anexact @LucieGueuning please shout.

**Comment by matthewberryman** [comment]
Example code https://codepen.io/brylok/pen/zawdJ

**Comment by matthewberryman** [comment]
@LucieGueuning @anexact please give this a try in our dev environment.

**Comment by LucieGueuning** [comment]
Not satisfy on my screen. Indeed, it looks like Missions Histories is under monitoring and assessment.
![image](https://user-images.githubusercontent.com/25951555/39056553-f84e2b9c-44ae-11e8-882e-86d438e587d7.png)

**Comment by matthewberryman** [comment]
subtabs going on to the second line is not something we can control - it's wrapped by the browser as there's not enough space and we can't give it more space. There's a line separating top level tabs from subtabs and we also distinguish between top level tabs and subtabs through capitalisation.
