### ISSUE TITLE
Loading contact - bug

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#376]
![image](https://user-images.githubusercontent.com/25951555/38807949-47a65bec-4176-11e8-8ede-4437d1a3f5b2.png)

**Comment by matthewberryman** [comment]
I can't reproduce this. Lucie can you please [refresh with cache bypass](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Google_Chrome) and retry? Possibly broken with some changes to clustering @mehrdadgit put in earlier and/or I also changed the missions handling on the landing page as part of an implicit request to add mission table in #372

**Comment by LucieGueuning** [comment]
It is now gone.
