### ISSUE TITLE
Typhon - ID 44 should be delete from the prod environement

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#383]
It was for the live-demo of presentation
![image](https://user-images.githubusercontent.com/25951555/39054683-2d92328a-44aa-11e8-9911-1f0f7651a052.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/39054724-48804582-44aa-11e8-9ea1-343f6c54f4fe.png)

**Comment by matthewberryman** [comment]
(ignore commit message, not relevant for a DB entry change - I tagged wrong issue by mistake)
