### ISSUE TITLE
'Mission Histories' should be 'MSF Past Responses'.

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#385]

**Comment by LucieGueuning** [comment]
Should be MSF Past Responses. It is not the case currently

**Comment by matthewberryman** [comment]
I’d changed all references to “Mission Histories” but there was one on events page I’d  missed as it was written as “Mission History”. I’ll change that one later today.

Sent from my iPhone

On 19 May 2018, at 00:31, Lucie Gueuning <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be MSF Past Responses. It is not the case currently

**Comment by LucieGueuning** [comment]
need to be 'MSF Past Responses' and not 'Mission History'

**Comment by LucieGueuning** [comment]
In the menu on landing page/event page, it is not yet the case.

**Comment by matthewberryman** [comment]
It now reads MSF Past Responses in both menus. Try refreshing your browser cache if you can't see it.
<img width="439" alt="screenshot 2018-05-21 19 08 10" src="https://user-images.githubusercontent.com/2288238/40299690-6e0bad1c-5d2a-11e8-9bbb-3e657a565df0.png">
<img width="644" alt="screenshot 2018-05-21 19 08 36" src="https://user-images.githubusercontent.com/2288238/40299750-9c575f5e-5d2a-11e8-8749-91d3e7196fdb.png">

**Comment by LucieGueuning** [comment]
Misunderstandings: Need to be MSF Past Responses on the menu of the map on all maps (where we can turn layers on and off)

**Comment by matthewberryman** [comment]
Ok in future please be clearer in bug reporting.
