### ISSUE TITLE
Why only 135 contacts on my landing page?

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#389]
![image](https://user-images.githubusercontent.com/25951555/39225370-ddfdf7b6-4843-11e8-972f-e1cd1c5d5d67.png)

**Comment by matthewberryman** [comment]
I've fixed up some cookie bugs plus those are only stored on a browser basis (are you on a different computer with travel?) and so you would have resorted to default settings, which per your [request](https://github.com/MSFREACH/msf-reach/issues/355#issuecomment-382357562) is now off for non-MSF(-staff) contacts. If you turn non-MSF contacts back on then this setting will be kept and the rest will show up.
