### ISSUE TITLE
an error occurred

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#393]
when trying to add contact, Remi experienced the following message when hitting the button 'submit' 

'an error occurred'. He is on edge. 

asap for the demo

**Comment by matthewberryman** [comment]
Known bug previously advised per https://github.com/MSFREACH/msf-reach/issues/332#issuecomment-383271814 - closing this duplicate issue. Active use of the rest of the system (refresh first) resolves in my experience. Too complicated now to fix before demo, short of rolling back requested major work in #332 out of prod prior to demo (leaving it in test environment).
