### ISSUE TITLE
email notification of private contact shares

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#399]
@LucieGueuning I've broken this bit off from #332  (the rest of that is now done) - I want to wait until @mehrdadgit has done some work on email as part of https://github.com/MSFREACH/msf-reach/issues/227 (separate to scheduled reminders in https://github.com/MSFREACH/msf-reach/issues/234 ) as #227 will bring in some email code that I then want to reuse for this.

**Comment by LucieGueuning** [comment]
This is amazing and well tested with colleagues here. 
Few comments: 
- one space needs to be remove before Kind Regards (on the email message)
- when clicking on the link of the contact, the person end up to the landing page and not to the specific contact card.

**Comment by matthewberryman** [comment]
* one space needs to be remove before Kind Regards (on the email message): fixed
* writing MSF REACH in capital letter for consistency: fixed
* logo or image not loading: I checked and URL is correct, I'm guessing it's not showing based on your email security settings (under mine it doesn't show up at all). The only way I can avoid these sorts of problems is to not have an image, so I've removed it.
* link to contact: cannot be done yet as this depends on https://github.com/MSFREACH/msf-reach/issues/408 - this item I have added to that list

**Comment by LucieGueuning** [comment]
tested and here is my feedback: 
1. take some time to suggest name from MSF address book. Any solution easy to make it faster, or maybe any tweaks or bugs fix in the code for speeding up the suggestions? 
2. We should have a proper button to press for sharing. One more step and not only selecting the person from suggestion that makes the sharing happening. 
![image](https://user-images.githubusercontent.com/25951555/48487562-826e6e80-e816-11e8-95df-2059c05ebc6e.png)

3. confirmation message on REACH is all good!
4. email received is good, but has a bug in the hyperlink to the contact: 
![image](https://user-images.githubusercontent.com/25951555/48487661-c5c8dd00-e816-11e8-83cc-251b28cddc17.png)
5. Subject should be: **Contact sharing notification**. for better english, no? Please let me know based on your better knowledge of the language.

**Comment by matthewberryman** [comment]
1. Not really as far as I can see, limited by latency and also search time from AD server.
2. @mehrdadgit can you please take a look at this one.
3. great.
4. I think I've resolved this by updating the templating method used for this (based on one example in our code that is working). Please test.
5. Correct, have adjusted this.

**Comment by matthewberryman** [comment]
@mehrdadgit thanks, I just merged to issues/174 branch

**Comment by LucieGueuning** [comment]
as requested, during our call: 
- button 'Share' tested and working well
- email received with the hyperlink, perfect
- one bug though: 
![image](https://user-images.githubusercontent.com/25951555/48562415-0e9d9600-e8ea-11e8-9909-6daeac419767.png)

**Comment by matthewberryman** [comment]
bug is separate issue, see https://github.com/MSFREACH/msf-reach/issues/680
