### ISSUE TITLE
select past missions and contacts for linking with events

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#40]

**Comment by matthewberryman** [comment]
@LucieGueuning The easiest and cleanest way is to have a field for each contact that lists a single event (if any) that they are working on, rather than having multiple events per contact, or doing it the other way around (i.e. keeping a list in the event fields of relevant contacts). But this assumes that a person will be working on at most one event on the ground at a time.

**Comment by LucieGueuning** [comment]
exactly, need to have a list of MSF staff working per event

**Comment by matthewberryman** [comment]
Ok but per https://github.com/MSFREACH/msf-reach/issues/179#issuecomment-364488784 you said to support people who aren't in contacts, so free form (as is) is fine although I will flag a bug in nationality over on the other issue.

So for this issue, aside from listing MSF human resources, we also need a separate ability to save other contacts. Should this look like the saved tweets then?

**Comment by LucieGueuning** [comment]
the system with AI and ML will have mission history and contacts linked to the specific event

**Comment by matthewberryman** [comment]
Done bar ui changes pending in #537
