### ISSUE TITLE
table of contacts on landing page

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#408]
@LucieGueuning, @anexact 
need to define what is defined here as space is much more limited than on the events page

**Comment by LucieGueuning** [comment]
- full name 
- type of contact
- speciality

with the following layout: 
![image](https://user-images.githubusercontent.com/25951555/40429032-8f59dc62-5e99-11e8-9c95-7b9b0cc1aa3e.png)

**Comment by LucieGueuning** [comment]
- Name
- type of contact 
- specially

Cf. picture by WA

**Comment by matthewberryman** [comment]
URL parameter for selecting contact

**Comment by matthewberryman** [comment]
(sorry accidentally closed)

**Comment by matthewberryman** [comment]
country rather than speciality (if still room after name and type)

**Comment by LucieGueuning** [comment]
as per call: 
- Name
- Organisation
- Country 
- Type of contact

If feasible in term of UI
