### ISSUE TITLE
put name of event on report card

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#41]
Change 
https://github.com/usergroupcoop/msf-reach/blob/master/public/report/index.html#L36
to read "MSF would like to request any information you may have about an event, " + name_of_event_this_report_is_associated+ ", that may be happening in your area."

**Comment by mehrdadgit** [comment]
OK; assuming we hit the API for this and not passing it through GET params ?

**Comment by matthewberryman** [comment]
Yes I would hit API for it.

**Comment by LucieGueuning** [comment]
Good on report card in a new browser window. Not yet done on the pop-up window on the event page.
