### ISSUE TITLE
layers and tab names consistent

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#415]
cc @LucieGueuning

**Comment by LucieGueuning** [comment]
for every map, for every tab, we need to have: 
- Previous MSF Responses
- Ongoing MSF Responses 

The word 'Responses' includes monitoring, explo, intervention status. 
I have asked in the manson unit and 'previous' and 'ongoing' seems the best for them. 
Fianl decision for this phase. Thank you!

**Comment by matthewberryman** [comment]
@LucieGueuning 
Because of the way the user preferences for map layers are saved (because of the way the mapping library we use works), this fix for this consistency will reset the MSF ongoing and past response settings on the map, but then going forwards the system will remember these user preferences.

**Comment by LucieGueuning** [comment]
On layers selection, on landing page map, 'previous MSF responses' don't appear anymore
