### ISSUE TITLE
Bugs for contact entry? 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#422]
![image](https://user-images.githubusercontent.com/25951555/40430329-d387155a-5e9c-11e8-9e93-9bb20e002e52.png)

**Comment by matthewberryman** [comment]
Not a bug, on checking the logs it's actually flagging that that we were supplied with duplicate entries which we need to eliminate as a matter of general data hygiene but also so we can reference people properly for editing removal #227. I've opened a database ticket for that https://github.com/MSFREACH/msf-reach-schema/issues/51
