### ISSUE TITLE
Contact card updates

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#425]
- remove fields: DOB, Gender, Profile/Speciality, Fax, Web. 
- Change field location to: please indicate the location where you are currently based. Please update it as soon as you move. 
- HQ staff (OC/PS). from the 'current employment status' need to have three options: field worker (national staff); field worker (international staff); HQ staff (OC/PS). Meaning we collapse all the last one into one. 
- OC: the next field should only be called 'Operational Center' instead of OC/PS/BO/MISSION
- one box for the 4 fields (Mission, Project, etc.) (if any)

**Comment by LucieGueuning** [comment]
follow-up on that one?

**Comment by matthewberryman** [comment]
@LucieGueuning can you expand on what you mean by the OC bullet point?

**Comment by matthewberryman** [comment]
@qclin thanks for your work on this thus far in https://github.com/MSFREACH/msf-reach/tree/issues/425 (can you please add #issue_number to all commits related to an issue for tracking, and include keyword "fixes"/"closes" less quotes when you've tested it and in your view it fixes it). I've written and tested (locally) some code for updating the database for older entries in https://github.com/MSFREACH/msf-reach-schema/compare/master...dev#diff-fe920b8a3fa450a8c447d5054e4dbb80 

@LucieGueuning awaiting your response on https://github.com/MSFREACH/msf-reach/issues/425#issuecomment-408261363

**Comment by LucieGueuning** [comment]
sorry for delay. I updated the description of the first comment for more explanation and clarity. All clear?

**Comment by matthewberryman** [comment]
yes thanks @LucieGueuning :)

**Comment by LucieGueuning** [comment]
- need to **remove** the three last fields of 'current employment status': OC staff; PS/BO staff; Satelite staff
- wording: 'MSF peers' tick box should be 'Former national staff' (see picture)
![image](https://user-images.githubusercontent.com/25951555/43527280-2098a056-959e-11e8-9c7e-be19442c4857.png)

**Comment by matthewberryman** [comment]
@LucieGueuning noting per timeline above that @qclin already got onto the collapse of those MSF employment types before your comment, and I've since also updated the database for previously-entered entries made before this further field change (https://github.com/MSFREACH/msf-reach-schema/issues/60). I've changed the wording for MSF Peer -> Former Staff per your most recent comment.

**Comment by LucieGueuning** [comment]
- no job title asked when choose 'Current MSF staff'
- red star for 'employment status' and 'operational center': to be removed
<img width="368" alt="capture d ecran 2018-08-14 a 10 11 04" src="https://user-images.githubusercontent.com/25951555/44083309-876a3ad0-9fab-11e8-8d4e-08bd8a1f4e1f.png">
