### ISSUE TITLE
Share contact - UI

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#428]
UI needs to follow the same interface than Office 365 suggestions of people. 
![whatsapp image 2018-05-23 at 5 24 55 pm](https://user-images.githubusercontent.com/25951555/40437833-5053c25c-5eae-11e8-9c60-12ea76b91137.jpeg)

**Comment by matthewberryman** [comment]
Office 365 is closed source product so we can't copy UI
