### ISSUE TITLE
Twitter search advanced

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#431]
To filter less than hundreds of results and having the relevant ones.

**Comment by matthewberryman** [comment]
Initial twitter search based on event name (now free form and editable), so reliant on users making sensible suggestions there—I have not received any futher advice on #89 to suggest using something else, plus results shown are already partly sorted by time fur currency, and search term itself can be modified.

**Comment by matthewberryman** [comment]
Also noting work completed in https://github.com/MSFREACH/msf-reach/issues/569
