### ISSUE TITLE
remove MSF peers option from the contact card

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#438]

**Comment by matthewberryman** [comment]
Maybe make this peers option dependent on whether it's MSF entered or not.

**Comment by matthewberryman** [comment]
7954c64 didn't quite fix it due to to misplaced style. Proper fix coming soon.

**Comment by LucieGueuning** [comment]
As per skype call on Tuesday 26.06, we need to have on contact card for both MSF staff entering contact details or contact entering their own contact details the category dropdown menu + check box for association members + check box for 'Former MSF Staff'

All good? @matthewberryman
