### ISSUE TITLE
Mobile phone network (SMS) ability for reporting

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#441]

**Comment by matthewberryman** [comment]
Mobile phone reporting already supported and demoed

**Comment by matthewberryman** [comment]
Means SMS reporting - this is doable in but need to think about UX for this and there are costs associate with receiving and sending SMS that I need to review and communicate.

**Comment by matthewberryman** [comment]
Suggestion to have numbers (1-4) for category of reports. Address can be "city, country" but then geocoding would always default to city centre.
