### ISSUE TITLE
layers selection preferences are not memorise by the system on REACH

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#456]
reported by Natasha on 31.05

**Comment by matthewberryman** [comment]
I just tested them again then on dev site and couldn't reproduce. Which layers are affected, what is current browser?

**Comment by LucieGueuning** [comment]
She is on her mac and layers that are always on even though she is putting them off is: contact, ongoing MSF projects, reports.

**Comment by matthewberryman** [comment]
I tested those again and can't reproduce. Still awaiting feedback on which browser.

**Comment by matthewberryman** [comment]
Closing; no further feedback and I can't reproduce.
