### ISSUE TITLE
On prod, on landing page, on ongoing MSF response table, there is a box to be manually deleted

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#460]
![image](https://user-images.githubusercontent.com/25951555/40873613-a00eba4a-665b-11e8-9202-f3dacf15afe5.png)

**Comment by matthewberryman** [comment]
Events can be closed off and will be removed, but it seems the problem here is the missing hyperlink to open and then close the event (?); the hyperlink is not showing as no name was entered. In such cases I propose adding "(no name entered)" in that box so the hyperlink shows.

**Comment by matthewberryman** [comment]
Confirmed as an empty name issue. As previously requested this is optional (see  https://github.com/MSFREACH/msf-reach/issues/89). In such a case I fill in the Twitter search terms auto fill, but I can't use that approach here as it's based on the type which is already displayed so I'd be doubling up if I used that same approach here. I would suggest going ahead that we do put an event name in; that will help AI too. Anyway for now, in the absence of feedback, I have put "(no name entered)" as the name and you can click on the hyperlink and close event to remove it from display (noting other issues still to work on on deletion etc.).

**Comment by matthewberryman** [comment]
cc @anexact for comment
