### ISSUE TITLE
edit button on basic data and other field need to be more obvious on event page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#463]
They (=users) need to scroll down to find the edit button and they are not doing it intuitively

![image](https://user-images.githubusercontent.com/25951555/40873654-9ac397a8-665c-11e8-9251-c7f08d013db4.png)

**Comment by matthewberryman** [comment]
The basic fields will be editable as part of work on #363 without need to scroll down.

@mehrdadgit
