### ISSUE TITLE
'acknowledge' tick box on contact card not coherent if it is for yourself - confusing

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#468]

**Comment by qclin** [comment]
@matthewberryman  @LucieGueuning resolved on ticket #593

**Comment by matthewberryman** [comment]
Wording changed to "I acknowledge I give permission for my contact details / have permission from contacts I am entering" to cover both cases - we don't know until next screen whether they are entering theirs or someone else's.

**Comment by LucieGueuning** [comment]
ok, all good.
