### ISSUE TITLE
Notification on edit part

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#470]
- need to see the entire box of explanation
- need to have the cursor same place than left for another page/tab on browser

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/42935963-d8770d86-8b42-11e8-932c-8e6319fae179.png)


URGENT! need to be solved!

**Comment by matthewberryman** [comment]
@mehrdadgit Can you please make this one a multi-line text input

**Comment by mehrdadgit** [comment]
Yes; will get to it tomorrow.

**Comment by LucieGueuning** [comment]
Not working. even after clearing caching.

**Comment by matthewberryman** [comment]
@LucieGueuning this working in dev. I will put it on test&prod soon.

**Comment by matthewberryman** [comment]
The editing on modal is still working, but since I last commented the in-line editing has broken with my work on #434 . @mehrdadgit can you please fix the bug I've introduced

**Comment by matthewberryman** [comment]
Turns out it was a bug unrelated to my changes, https://github.com/MSFREACH/msf-reach/issues/538 , now fixed in dev.

**Comment by matthewberryman** [comment]
@LucieGueuning now deploying this to test and prod
