### ISSUE TITLE
How to delete completely from REACH (Mission History or ongoing project) an event? 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#473]
- need to differentiate Mission History, from ongoing MSF response, from Monitoring and Assessment event. 
- need to differentiate monitoring and assessment event that are closed without MSF intervention (that is not considered as Mission History)

refer to #481

**Comment by LucieGueuning** [comment]
on this issue specifically, being able to delete events from the database (admin or operators can entirely delete events)

**Comment by matthewberryman** [comment]
@LucieGueuning ready for test in dev / test.

**Comment by LucieGueuning** [comment]
Great work. Please merge to prod and let Fei knows about it asap, so that she can delete Mission History from the database. Thanks!

**Comment by mehrdadgit** [comment]
Sure @matthewberryman will have a go tonight. Just noting that, only for `mission` API, all update endpoints were already `ensureAuthenticated` meaning any user can update; so I did the same for delete. Should I change  both update and delete to `ensureAuthenticatedWrite` or leave as is?

**Comment by matthewberryman** [comment]
Yes missions should be ensureAuthenticatedWrite - I will update the API today, and also at top of mission modal and top of event editing tab on events page add some text per #432.

If you could remove the delete buttons tonight that would be great.

I will do this in dev and merge to issues/174 and could you please do the same.
