### ISSUE TITLE
Notification by email

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#488]
Users can follow event or can be tagged on event (in edition or creation). If there are updates, they receive an email.

**Comment by matthewberryman** [comment]
duplicate 336	"We need some kind of alert for a new notification or new chat message. I think that was already planned, right?"

**Comment by LucieGueuning** [comment]
operator need to be able to not send email after updates. 
after edition, pop up asking send email to subscription: yes or not

**Comment by matthewberryman** [comment]
This feature is already covered by #336, please add details there.
