### ISSUE TITLE
GIS data - MSF Presence to integrate

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#495]
discussion on 21st of June with GIS unit on OCG

**Comment by matthewberryman** [comment]
Here's the full list of properties for each each presence. Note that the open_date and close_date are numbers representing number of milliseconds since Jan 1st 1970 00:00 UTC, which I convert to human-readable dates.

```javascript
var feature = {properties:
   { objectid: 1,
     iso3: 'country code',
     name: 'presence name',
     name_alt: 'alternative presence name',
     pcode: 'toBeSet',
     address_1: '',
     address_2: '',
     postal_code: '',
     locality: '',
     state: '',
     country: 'Australia',
     operational_centre: 'ocp',
     cell: '',
     type: 'coordination',
     project_code: '',
     intervention_type: 'emergency',
     project_mode: 'handson',
     open_date: 1528259104000,
     open_date_precision: 'month',
     close_date: null,
     close_date_precision: '',
     confidentiality: 'msfpublic',
     note: '',
     geo_precision: 'gps',
     edited_by: 'ocpadmin',
     edit_date: 1528259105000,
     source: 'MSF',
     globalid: '{uuid}',
     mission_code: '',
     parent_globalid: '{uuid}' }};
```

**Comment by matthewberryman** [comment]
@LucieGueuning This is in dev and test environments. It's off by default so you will need to turn it on in the layer selection box. I can adjust that setting, and marker size, and popup display (bearing in mind the full list of properties in my first comment above).

**Comment by matthewberryman** [comment]
There's a timing bug I noticed in testing. If it doesn't list an option in the layer control then try refreshing the page and that should resolve it. I will fix this bug tomorrow.

**Comment by matthewberryman** [comment]
timing bug should be fixed; I will test when it deploys to dev & test environments in a few minutes.

@LucieGueuning any feedback on UX particularly fields displayed?

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/41341635-14f61ecc-6ef2-11e8-8a5c-56747896a5ca.png)

Comment/feedback:
1. This is the info that we need at least!
2. Why we do not have the color code by OC? All are in blue, why not following their color code. 
3. UI: OCB needs to be in capital letter

**Comment by matthewberryman** [comment]
They're not following any colour code by OC as I haven't been supplied with any colour code. If you can send me a list of ideally RGB (preferred) or CMYK colour codes for each OC I can use that.

**Comment by LucieGueuning** [comment]
token expired again?

**Comment by matthewberryman** [comment]
Correct, it's expired despite me specifying a year expiry.
For the OCG presentation, can you let me know the exact time the demo is? That way I can ensure it will work for the demo. In general I will need MSF IT team to fix this, and will add some more error handling around it for when the token does expire (so that it doesn't show the layer in the control or try and render the data).

**Comment by LucieGueuning** [comment]
ok, meeting in OCG is from 9:00am (CET) to 17:00 (CET).

**Comment by matthewberryman** [comment]
Sorry, accidentally closed as I used the keyword "fixed" in a commit before we realised there was a token generation issue from the upstream server.

**Comment by matthewberryman** [comment]
Token issue resolved.
