### ISSUE TITLE
How can we edit Mission History into REACH? 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#499]
We are hiring data entry person who will clean all the data and input the right info into mission history (white icon) - closed mission into REACH. But today we can't edit those. How can we enable this for her to start working on that?

**Comment by matthewberryman** [comment]
@mehrdadgit can you work on this first, then resume your work on the open event editing UI changes.

**Comment by matthewberryman** [comment]
just checked and we do have PATCH and PUT for /api/events (see source) - so this should be mostly just UI work. @mehrdadgit sing out if you think I need to change anything on the API

**Comment by matthewberryman** [comment]
Have merged in WIP; @mehrdadgit please continue work in dev.
Still to do (not an exhaustive list):
* Manager arrival and departure dates need description in display mode.
* Check for https:// at start of entered sharepoint link.
* Make sure that hyperlink goes to correct site when displayed.

There's also a spreadsheet I will email you a link soon to consider in terms of fields for editing and display. I will talk it through with you on Monday.

**Comment by mehrdadgit** [comment]
^^ Those dot points done @matthewberryman 

(And just realised we forgot to discuss spreadsheet today.. I will come see you tomorrow )

**Comment by matthewberryman** [comment]
Thanks.

You seemed busy today and I was also a bit busy meetings a deadline so yes, let’s catch up tomorrow :)

Sent from my iPhone

On 25 Jun 2018, at 22:00, Mehrdad <notifications@github.com<mailto:notifications@github.com>> wrote:


^^ Those dot points done @matthewberryman<https://github.com/matthewberryman>

(And just realised we forgot to discuss spreadsheet today.. I will come see you tomorrow )

**Comment by matthewberryman** [comment]
Still ongoing. @mehrdadgit try and avoid use of keyword "fix" unless the whole issue (not just individual bugs) are fixed.

**Comment by matthewberryman** [comment]
@LucieGueuning please test in dev

**Comment by matthewberryman** [comment]
@mehrdadgit can we make the modal fit in the window / move edit button to the top, so it's clearer?

**Comment by mehrdadgit** [comment]
Done @matthewberryman

**Comment by LucieGueuning** [comment]
All good! Thanks for the hard work on that one. I will re-open it if any bug noticed while entering data.
