### ISSUE TITLE
Add LRA Crisis Tracker layer

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#505]

**Comment by matthewberryman** [comment]
@LucieGueuning please review this in dev/test environments. You will need to turn the layer on (it's off by default but I can change that) and pan the map to Africa.

**Comment by matthewberryman** [comment]
@LucieGueuning please review on dev/test

**Comment by matthewberryman** [comment]
Just noting that I map all activities by LRA since the start of the year, but their API is pretty flexible, e.g. I could request activities by all actors, or over a different time period (but I don't want to request too much data as it will slow things and put a load on their server), or we could filter by the verification rating in the API.

Example data with the different fields available:

```javascript
        {
            "id": 357770,
            "public_display_note": "After looting Yangou Dacko the same day, a group of men, women, and children suspected to be LRA looted the village of Yangou-Péndéré, CAR, at 15:00. The assailants spoke Acholi, Lingala,and Sango.",
            "latitude": 8.529,
            "longitude": 23.249,
            "verification_rating": 3,
            "lra_verification_rating": "Medium",
            "irn": "IRN-7804",
            "community_id": 489,
            "community_name": "Yangou-Péndéré",
            "community_region": "Haute-Kotto",
            "community_country": "CAR",
            "start_date": " May 29, 2018",
            "lra_attack": true,
            "uag_attack": false,
            "returnees": false
        }
```

**Comment by LucieGueuning** [comment]
filter by verification rating + over a different time period is a good idea. 
Need at least: 
public display
lra_verification_rating
community name
community region
start date

**Comment by matthewberryman** [comment]
@LucieGueuning what verification rating & time period do you want to filter by? I can hard code some defaults in for now if you like.

**Comment by matthewberryman** [comment]
I've got those fields in; just noting that public_display is called "summary" so it's consistent with other RSS feeds

**Comment by LucieGueuning** [comment]
Ok great. Can we have an icon (same than other RSS feed) for consistency? Like an icon that represent 'attacks' with square boundary (as the other). Make sense? 

Hyperlink doesn't work: 
![image](https://user-images.githubusercontent.com/25951555/41402210-9d59f884-6fb9-11e8-962c-11be402a4219.png)

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/41408672-5ead6b2c-6fcb-11e8-840f-737053af8cce.png)
 @talltom, any help on icons from bootstrap ?
