### ISSUE TITLE
Integrate Shapefile via REACH

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#506]
cf. zip file by email

OCG meeting

**Comment by matthewberryman** [comment]
got the data; today I have converted the point data to geojson and then I need to import that into the database and write some API hooks (that I will do tomorrow) and then work on UI (early next week)

**Comment by matthewberryman** [comment]
(tagged code commit abc87f7  with wrong issue number, it's actually for #507 and I will comment there on that)

**Comment by LucieGueuning** [comment]
Keep in mind: Meeting OCG on 20th of June! Thanks Matthew

**Comment by matthewberryman** [comment]
Health site data fields:
```javascript
let health_site = {
  "type": "Feature",
  "properties": {
    "OBJECTID_1": 1,
    "iso3": null,
    "name": "Name",
    "pcode": null,
    "level": 0,
    "note": null,
    "opendate": null,
    "closedate": null,
    "editedby": null,
    "editdate": null,
    "source": "MSF",
    "statut": 0,
    "type": "reference general hospital",
    "name_alt": null,
    "contact": null,
    "nb_doctors": 0,
    "nb_nurses": 0,
    "opd": 0,
    "ipd": 0,
    "maternity": 0,
    "surgery": 0,
    "nutrition": 0,
    "pharmacy": 0,
    "laboratoy": 0,
    "radiology": 0,
    "mcp": 0,
    "birth_per_": 0,
    "patient_pe": 0,
    "electricit": null,
    "coldchain": null,
    "nb_toilet": 0,
    "water_quan": 0,
    "water_sour": null,
    "water_chlo": null,
    "org1": null,
    "org1_suppo": null,
    "org2": null,
    "org2_suppo": null,
    "desease1": null,
    "desease2": null,
    "desease3": null,
    "outbreak1": null,
    "outbreak2": 0,
    "outbreak3": 0
  }
}
```

**Comment by matthewberryman** [comment]
village/city fields
```javascript
var city = { "properties": {
  "ID": 0,
  "iso3": "cod",
  "name": "city_name",
  "note": null,
  "type": "city",
  "pcode": "COD000001",
  "source": "source",
  "OBJECTID": 1,
  "name_alt": null,
  "startvalid": "1970/01/01"
}};
```

**Comment by matthewberryman** [comment]
msf presence data
```
let msf_presence = {"properties": {
  "iso3": "cod",
  "name": "name",
  "note": "Nato_code_word_1 Nato_code_word_2",
  "type": "coordination",
  "pcode": "COD000001",
  "adress": "address",
  "source": "source",
  "status": 1,
  "OBJECTID": 1,
  "editdate": "1970/01/01",
  "editedby": "email@example.net",
  "opendate": null,
  "closedate": null
}};
```

**Comment by matthewberryman** [comment]
A data dictionary would be very helpful.

Questions for @LucieGueuning :
* Is "pcode" postcode?
* What is the meaning and range of "statut" (status) number for the health site data? For presence data?
* Similarly, what is the meaning and range of level for health site data?
*  OPD/IPD = out patient department / in patient department ? Lucie to confirm.
* What does "MCP" mean?
* "water_quan" <- I assume this is water quantity? What are the units (kL?)? 
* "birth_per_" births per what? Per 1,000?
* For presence, what are the meaning of the (phonetic alphabet) Nato code words in the note field?
* What, if any, is the overlap between this presence data and the other MSF presence data?
* For the following, what does the number mean? A binary yes/no? Number of staff? Number of units/wards? Number of beds (for surgery and maternity)? Noting that in almost all cases this is 0.
  - "maternity": 0,
  - "surgery": 0,
  - "nutrition": 0,
  - "pharmacy": 0,
  - "laboratoy": 0,
  - "radiology": 0
* Does null mean no data was collected? Or should be interpreted as zero? 
* For type, is there a defined set of possibilities for this, if so, what?

**Comment by matthewberryman** [comment]
@LucieGueuning this is in dev/test (noting separate emails about test environment) ready for you test. Some notes:
* Layers are off by default
* There's a lot of village data and even with clustering this layers is a bit slow.
* Note that I have updated my list of questions in https://github.com/MSFREACH/msf-reach/issues/506#issuecomment-397920354 so please refer to that - do not forward the original list of questions on (if you received the first version via GitHub notification email).

**Comment by matthewberryman** [comment]
leave off villages for now
