### ISSUE TITLE
Open Map once getting on REACH for worldwide and not specific to SEA 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#507]
OCG meeting

**Comment by matthewberryman** [comment]
(on dev/test for now)
Map opens at view of whole world. As you then zoom and pan the map it saves the current map bounds (in cookies), so as users refresh / come back to the landing page it will open at the same view they had before.

**Comment by LucieGueuning** [comment]
Ok, great. Move to prod?
