### ISSUE TITLE
need to be able to filter by 'peers' and ' association members'

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#511]
![image](https://user-images.githubusercontent.com/25951555/41470905-ed0b6b06-70a9-11e8-9d20-2e020376cd33.png)

Can we add 'peers' and 'association members' in the list to filter?

**Comment by matthewberryman** [comment]
Peers and associates are separate fields ( https://github.com/MSFREACH/msf-reach/issues/179#issuecomment-360736534 ) so these need to be added as separate UI elements (taking up space), also you'd requested that we remove the peers option in https://github.com/MSFREACH/msf-reach/issues/438 so we'd just be adding search for associates unless fields have changed again???

**Comment by LucieGueuning** [comment]
- wording mistake : 'Association Member' instead of 'MSF Associate'
- add 'Field Workers' to the dropdown option. Note that we have this category on contact card ('current employment status')

**Comment by matthewberryman** [comment]
Wording change fixed, new feature request covered in separate issue.
