### ISSUE TITLE
Removal of DRC data + test data from the prod site. 

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#519]
Would you mind delete from the production site the DRC data including: 
- LRA crisis RSS Feed from the map and so the menu on/off selection
- DRC layers (shapefiles) from the map and so the menu on/off selection
- Contacts on DRC. 

Would you mind delete from the production site the data generated by the test demo including: 
- Event ID 52; Event ID 53; Event ID 54

**Comment by matthewberryman** [comment]
@LucieGueuning just double checking you mean the production site for those events? As there are now two separate sets of events on prod and test and I thought you were using test for the demo as discussed?

**Comment by matthewberryman** [comment]
In particular 52 on *test* is DRC but others (incl. 52 on *prod* ) are not.

**Comment by matthewberryman** [comment]
After taking backups, I have removed from all sites (prod and test, but also dev):
* LRA crisis RSS Feed from the map and so the menu on/off selection
* DRC layers (shapefiles) from the map _and databases_ and so the menu on/off selection
* From the database (and hence display on the map and tables): Contacts on DRC.

I removed from dev to avoid having the UI elements re-appear on next merge into master. If necessary we can add them back in but subject to a configuration variable so they appear on dev only, for example.

Awaiting your feedback on which environment(s) you need events removed from.

**Comment by matthewberryman** [comment]
Following confirmation from @LucieGueuning those events removed from prod only.
