### ISSUE TITLE
bugs on landing page from new work

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#520]
jquery-3.3.1.min.js:2 Uncaught TypeError: option changeMonth is not recognized!
    at Boolean.<anonymous> (bootstrap-datetimepicker.min.js:1)
    at Function.each (jquery-3.3.1.min.js:2)
    at Object.l.options (bootstrap-datetimepicker.min.js:1)
    at c (bootstrap-datetimepicker.min.js:2)
    at HTMLInputElement.<anonymous> (bootstrap-datetimepicker.min.js:2)
    at Function.each (jquery-3.3.1.min.js:2)
    at w.fn.init.each (jquery-3.3.1.min.js:2)
    at w.fn.init.a.fn.datetimepicker (bootstrap-datetimepicker.min.js:2)
    at HTMLDocument.<anonymous> (new-event.js:111)
    at l (jquery-3.3.1.min.js:2)

**Comment by mehrdadgit** [comment]
@matthewberryman Just letting you know, I had a look at this and realised that vue datepicker in mission edit modal is broken by removing the ref to vue-bootsrtap-datetimepicker.js

**Comment by matthewberryman** [comment]
Ok. I thought you were using the bootstrap one (not the different vue-bootstrap one) as you'd added the bootstrap one in https://github.com/MSFREACH/msf-reach/commit/e49ed01d6b78769dcacd13bfa9de3c229b5821bf - the source of these errors I was seems to have been because you had two competing libraries in the same namespace. Can you review all code for date pickers and pick one :)

**Comment by mehrdadgit** [comment]
Yes, it was because bootstrap-datetimepicker.min.js is a dependency of vue-bootstrap-datetimepicker (ref: https://github.com/ankurk91/vue-bootstrap-datetimepicker )... it's look like a tricky package dependency issue ... when I fix one the other one brokes; although we have both on event page working OK I guess? I will have a deeper look tonight.

**Comment by matthewberryman** [comment]
Could be a version mismatch, or something about the way I use jquery to add to the element? I'm out of time now, so yes please have a look tonight.

**Comment by mehrdadgit** [comment]
Seems fixed now. The issue was 
`jquery-ui-timepicker-addon` 

Let us avoid using any jquery-ui date/time picker across the board and stick to:
 
http://eonasdan.github.io/bootstrap-datetimepicker/ (When not using vue) 
https://github.com/ankurk91/vue-bootstrap-datetimepicker (When using with vue)
