### ISSUE TITLE
feedback on impacted area

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#521]
I created a new monitoring event @ REACH. One function is a must to have (or it is already exist but I don’t know), is to mark affected areas base on the severity at the map. It can be at county level, city level or province level. For example in this event, I would want to make one county as severely affected by the flooding due to the number of casualties and displaced population, while several other countries are mildly affected. Function to have more than one country affected. 

@anexact for ethnography
@matthewberryman for feasibility and relevance

**Comment by matthewberryman** [comment]
Splitting off multiple countries to https://github.com/MSFREACH/msf-reach/issues/534
