### ISSUE TITLE
.pdf/ .jpeg/ etc.  to upload on edit event (notification part)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#524]
a way to include images in the notifications, for example a PDF or JPEG of a typhoon path

feedback from Natasha on July 03rd

**Comment by matthewberryman** [comment]
to go under country tab

**Comment by LucieGueuning** [comment]
both ability to upload files and picture under country tab and as a notification

**Comment by matthewberryman** [comment]
I don't think that putting them in the country tab is a good, as these files are for an event, which (per other discussions) may be multiple countries. Therefore I suggest renaming "country details" to "event files".

**Comment by LucieGueuning** [comment]
No because we need to have country details tab with ability to upload files for country (e.i. policy paper, country guidelines, etc.) not related to specific event. Those files will be added to this tab once the event recognise the countries involved.

**Comment by matthewberryman** [comment]
To do it that way we'd need to:
1. Create a separate page, API, and change to the database schema to upload non-event files per country.
2. Support multiple country tabs per event.

Which is a major piece of work requested after the deadline for 2b issues to be filed, and is quite separate to support for notifications. I'll break this country tab issue of as a separate issue leaving this issue as files / notification only for @mehrdadgit to work on.

**Comment by matthewberryman** [comment]
Tested this (now in dev and will merge into prod soon) but for now the attachments are only listed in the notification section. 
For @mehrdadgit to-do:
Popups and table on landing page.
Latest notification on event page.

To save space since all of above are constrained, I think best to hyperlink from the notification.notification

**Comment by matthewberryman** [comment]
Just deploying a small change now to prod, dev and test to support PDFs/any other file type.

Sharepoint integration is https://github.com/MSFREACH/msf-reach/issues/576
