### ISSUE TITLE
edit modal needs to have scrolling within the modal

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#530]

**Comment by mehrdadgit** [comment]
Mission edit modal?

**Comment by matthewberryman** [comment]
Event edit modal.

**Comment by matthewberryman** [comment]
@mehrdadgit can you please bring the bottom of the modal up a bit. On my browser it sits right on the bottom of the window which still results in some scrolling of the whole page in some cases, plus looks a tiny bit untidy.
<img width="1448" alt="screenshot 2018-07-11 13 15 11" src="https://user-images.githubusercontent.com/2288238/42548842-854f5c6c-850c-11e8-8b5e-bd3aaf7400b2.png">

**Comment by matthewberryman** [comment]
@mehrdadgit I will follow up with you in person on Friday re #363
