### ISSUE TITLE
Request Geographical Search function for Cards/Contact/Event Creation

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#55]
Concern is with difficulty to find precise location for cards (where am I?), contact cards (where do I reside?), and event creation (where is the place I want to locate as the event?); request is to add a search function that is connected to Google address list (as discussed with MB previously) so that the address is pre-authorized (i.e. exists in Google address list).

**Comment by LucieGueuning** [comment]
search function on every map of REACH (even landing page).
