### ISSUE TITLE
check latest notification is actually latest notification

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#550]

**Comment by mehrdadgit** [comment]
I noticed this bug when I was doing #524 and have fixed it; should be fixed in dev

**Comment by mehrdadgit** [comment]
@matthewberryman  better to write to common function somewhere to get latest notification from the array of notifications, and without using sort... I will do that.

**Comment by matthewberryman** [comment]
@mehrdadgit yeah I know, I was just after a quick fix as I have a lot on :/

Can you please do this quickly and then work on #537 urgently.

**Comment by mehrdadgit** [comment]
Done @matthewberryman  I did some tests but please feel free to review https://github.com/MSFREACH/msf-reach/commit/5b0dbd2b2fb5f3f8a2a277ba1746c98a76840542 and let me know if there's any issue :)

**Comment by matthewberryman** [comment]
Great, thanks @mehrdadgit . I have reviewed and tested and will merge into master.
