### ISSUE TITLE
ignore reports on events page

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#553]
ignore reports already assigned to event on events page, similar to unassigned reports on landing page

**Comment by qclin** [comment]
@matthewberryman hey when select an event the reports disappear, is that the intended interaction ?
I need more explanation. or screenshoot

**Comment by matthewberryman** [comment]
yes, they should be removed from UI with a change of status to ignored (i.e. they're still in the system but with a status of ignored they don't get returned by the API per https://github.com/MSFREACH/msf-reach/blob/master/src/api/routes/reports/model.js#L18 )
