### ISSUE TITLE
error once we click on email address on test environment

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#561]
![image](https://user-images.githubusercontent.com/25951555/43526439-23961876-959c-11e8-94a0-9cc49f0e6e9c.png)

This is the case for all email address link
Pretty urgent as we have demo for South Africa tomorrow morning (CET). will do it in test environment.

**Comment by matthewberryman** [comment]
Not all cases, the map (leaflet) popups were ok. I will fix the rest.
