### ISSUE TITLE
depending on map pan, lng from leaflet can be out of range

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#571]

**Comment by matthewberryman** [comment]
fixed with https://github.com/MSFREACH/msf-reach/commit/aa2fb1a3a1bb491a81768c144bfc0e0ed62c3cfa 54579a5

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/49532152-cbfd2700-f8b3-11e8-9aa5-920957d5b802.png)

**Comment by matthewberryman** [comment]
@LucieGueuning I have repeatedly tested on Chrome and cannot reproduce this issue on zooming out, noting that we start with a sensible default zoom and also preserve the current zoom level and location across page loads.
<img width="385" alt="screenshot 2018-12-06 09 46 00" src="https://user-images.githubusercontent.com/2288238/49549117-e975d380-f93b-11e8-8147-727a5099b19b.png">

Can you please reset cookies and cache your end to make sure it's picked up the latest code and re-test, and also if still present please advise what browser this is.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/49582385-c7388180-f94c-11e8-93dc-7f41804a81f1.png)
Cache cleared. Map zoom out still too far.

**Comment by matthewberryman** [comment]
@LucieGueuning from your screenshot I can see the lngmin/lngmax contact (popup warning) aspect is resolved following your cache clear, and it seems as if the remaining aspect is just that you'd like the ability to restrict the zoom? I am just deploying a fix for that now to all environments.
