### ISSUE TITLE
On test environment, error message once uploading picture on report card

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#577]
![whatsapp image 2018-08-07 at 8 36 50 pm](https://user-images.githubusercontent.com/25951555/43827975-2960259c-9af3-11e8-8936-75c0d2cdd094.jpeg)

**Comment by matthewberryman** [comment]
The report bug was fixed earlier today my time with https://github.com/MSFREACH/msf-reach/commit/b15f63045ee7f2776fab7ae2a5907aad9460a513 (after that screenshot was taken) as noted on email and I tested again and it was still working fine.
