### ISSUE TITLE
edit save consistency

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#579]
Like for the event general information section, have a save button at the top of each in-line editing section, so the user doesn't need to do a cumbersome two step process of clicking done then scrolling down to press save button.

**Comment by matthewberryman** [comment]
cc @LucieGueuning

**Comment by LucieGueuning** [comment]
this whole thing can be confusing.  At the beginning, I just clicked "done" and thought that my new notification was saved.  I lost a few updates because I didn't click "save edits" at the bottom.

**Comment by LucieGueuning** [comment]
still edit in a new window that should be entirely removed right?
