### ISSUE TITLE
NEW LOGO

### ISSUE THREAD

**Issue by clgeros** [MSFREACH/msf-reach#58]
Please update all instances of the logo. Use the short file (Medecin sans frontieres | REACH).

https://drive.google.com/drive/folders/0Bw27FPU-gFxYQnlvU1VETHJvZUE?usp=sharing

Also, please remove the "MSF REACH" home tab and make the logo in the upper left corner the "home" tab instead.

**Comment by clgeros** [comment]
@matthewberryman new MSF REACH logo on login page and in upper left corner. If possible, they would like the logo in the upper left of the page to act as a "home button" and to remove the "MSF REACH" tab on the right of the screen

**Comment by matthewberryman** [comment]
Going to have to leave this as is for now due to limitations of the bootstrap library we're using in (it's doable but requires overriding a lot of default css).

**Comment by matthewberryman** [comment]
i.e. not enough time before I leave- still have a few other things to tweak

**Comment by clgeros** [comment]
OK.
