### ISSUE TITLE
'Save edits' button doesn't work (while not editing in a new window)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#580]

**Comment by LucieGueuning** [comment]
there's been a strong aftershock in Lombok and I had a glitch while updating REACH.  I clicked on "edit" beside the Notification label (?) and typed in the new info, clicked done, then clicked the "save edits" at the bottom, the new notification wasn't saved.  I then used the "edit in new window" option, and it worked.

**Comment by matthewberryman** [comment]
@qclin can you please take a look at Lombok event (I will get you a copy of prod database) plus also event 54 in test database that threw this error
```
vue.min.js:6 TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at getLatestNotification (common.js:31)
    at $e.notStr (events.js:1991)
    at zo.get (vue.min.js:6)
    at zo.evaluate (vue.min.js:6)
    at $e.notStr (vue.min.js:6)
    at $e.eval (eval at Ii (vue.min.js:6), <anonymous>:3:2512)
    at $e.t._render (vue.min.js:6)
    at $e.r (vue.min.js:6)
    at zo.get (vue.min.js:6)
```

Unless you think it makes sense to wrap these up soon (since this issue is high priority) as part of https://github.com/MSFREACH/msf-reach/issues/579

**Comment by matthewberryman** [comment]
`git bisect` reveals e74e4aa1f779c9e90e9729f7213e8de1c6e96e0c as the source of breakage of the save button (I think the marker that was commented out but I guess is used elsewhere). I will fork off the test issue as that looks to be different.

**Comment by matthewberryman** [comment]
No, not marker (that wasn't being used and safe to kill). I just checked out that particular commit and can't repro the bug - maybe git bisect was getting confused with some of the branches (?). I will retry.

**Comment by matthewberryman** [comment]
Sorry I think I read things wrong. Re-did git bisect and d8c3ff94b5037134d3a725579607a069e2a8f14c is the first bad commit (which makes more sense in terms of the changes)
