### ISSUE TITLE
not pictures showing on twitter feed - bug?

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#592]
<img width="1439" alt="capture d ecran 2018-08-14 a 10 20 54" src="https://user-images.githubusercontent.com/25951555/44083407-cd6ecd7a-9fab-11e8-9849-9b8b8be4f7f3.png">

**Comment by qclin** [comment]
@LucieGueuning it's the twitter api iframe, you need to wait a few seconds and then it will load in all the media

**Comment by matthewberryman** [comment]
<img width="531" alt="screenshot 2018-12-04 07 14 19" src="https://user-images.githubusercontent.com/2288238/49399034-4040a900-f794-11e8-938f-c84a6c243fb9.png">
