### ISSUE TITLE
GDPR - add a tick box on contact card + report card

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#593]
as we need the written consent once collecting personal data that this could be used and shared to other MSF entities. 

adding a tick box on the first slide of both report card and contact card that say: 'I consent (as written proof) that information can be shared with other MSF entities. Those information will be used to contact you if there is an emergency near your location of living, to request information for MSF assessment. It will be shared to MSF entities and partners (for technical reasons of development of REACH) only'. 

We need to say with which other corporate we share the data and for what kind of activities and purposes. Do the sentences up make sense to you @matthewberryman ?

**Comment by matthewberryman** [comment]
On contact & report card, I presume this should replace "Our promise to protect your privacy: Médecins Sans Frontières Hong Kong (MSF) promise not to sell, share or swap your personal information with any other company / organisation."? I think we still want to retain "The information you provide will be treated as strictly confidential and used in accordance to our Privacy Policy, found on our website." (with hyperlink) at the end of the text, so in full it would read "I consent that information can be shared with other MSF entities. Those information will be used to contact you if there is an emergency near your location of living, to request information for MSF assessment. It will be shared to MSF entities and partners (for technical reasons of development of REACH) only. The information you provide will be treated as strictly confidential and used in accordance to our Privacy Policy, found on our website." with hyperlink, and note I've removed "(as written proof)" as this is not in writing but is a tick box.

**Comment by LucieGueuning** [comment]
ok if this is tick box. Let me know once you are done for test.

**Comment by matthewberryman** [comment]
@qclin can you please change as a high priority, per https://github.com/MSFREACH/msf-reach/issues/593#issuecomment-413697124

**Comment by qclin** [comment]
@matthewberryman is it a required field to click next

**Comment by matthewberryman** [comment]
Yes

Sent from my iPhone

On 20 Aug 2018, at 19:01, Qiao Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


@matthewberryman<https://github.com/matthewberryman> is it a required field to click next
