### ISSUE TITLE
Skype chat not working

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#594]
![image](https://user-images.githubusercontent.com/25951555/44147080-6c2dc5b8-a08a-11e8-825e-cab161fb6352.png)

Button 'connexion' doing nothing when hitting it.

**Comment by matthewberryman** [comment]
This part is controlled by closed source Microsoft code, so is out of our control. Tested and working for me, in Chrome, without even having to allow popups, although that's something to check and is the most likely source of this issue as opening the Connexion/Sign in button will open a new window.

**Comment by LucieGueuning** [comment]
So it is useless if this is not working and wont be fixed. right?

**Comment by matthewberryman** [comment]
If it's broken (again, it's working for me, and have you tried allowing pop-up windows?) then you could raise a bug report directly with Microsoft, or we could look at removing it.

**Comment by LucieGueuning** [comment]
Yes 
![image](https://user-images.githubusercontent.com/25951555/44332832-f510bd80-a464-11e8-9a91-2dbdbde4275b.png)

**Comment by LucieGueuning** [comment]
sign up link working and opening a new pop-up windows. Connexion button not working.

**Comment by matthewberryman** [comment]
Because the script from MS only supports many->one person, decision was taken to remove this.
