### ISSUE TITLE
Field Definition on event page

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#60]
Once the Unique Event ID is created with the Create Button, request for the Event Landing Page to contain 5 additional expandable/collapsable tabs as follows:

### 1 Response [Tab]

Program Type: Check box: Food Distribution; Mental Health; NFI; Primary Health Care; Secondary Health Care; Sexual Reproductive Health; Shelter; Tertiary / Specialized Health Care; Therapeutic Feeding; Vaccination; WAT-SAN; Other (Specify)
+ Free text box 

Start Date of the MSF Response: Pop calendar

End Date of the MSF Response: Pop calendar

Location of MSF Response: Map-driven selection

Visa Requirements: Free text box

Operational Center: Check box (note: no default selection): OCA; OCB; OCBA; OCG; OCP

Medical Materials: Free text box 

Non-medical Materials: Free text box

Budget: Free text box 

Donors: Free text box

### 2 External Capacity [Tab]

Analysis of capacity on the ground: Free text box

Other organizations: Free text box

### 3 Medical Figures [Tab] 

Check box + free number box for Number of each case:
Births; Cholera Cases; Dengue Cases; Group Consoling or Mental Health Sessions; Individual Mental Health Consultations; Inpatient Cases; ITFC; Major Surgical Intervention; Malaria Cases; Measles vaccination; Measles cases; Meningitis vaccination; Migrants / refugees rescued at sea; NFI kits distributed; Outpatient Cases; SGBV Cases; Shelter kits distributed; Other (Specify)

### 4 Staff Resources [Tab]

in this section, the Operator requests the ability to add individuals from local staff as follows:

NAME: Free text box
FUNCTION: drop down menu: Admin; HR; Finances; Logistics; Medical/Paramedical; Mental Health; WAT-SAN; Other 
CONTACT: Free text box
COMMENT/EVALUATION: Free text box
HIRED BY MSF: Pop up calendar
NATIONALITY: Drop down menu: Local / Expat

### 5 Reflection [Tab]

Practical Details / Comments: Free text box
Recommendations: Free text box

**Comment by LucieGueuning** [comment]
Under review by myself

**Comment by LucieGueuning** [comment]
- 'opened' field on event page is not clear enough (
![image](https://user-images.githubusercontent.com/25951555/36841957-026bd834-1d42-11e8-88a0-14fea25e9a6d.png))

Need to be in two separate lines as below: 
Date: 2018-03-01
Time: 11:11:51

**Comment by LucieGueuning** [comment]
**1. first table of the current view with the following information (coming from the creation of the event)**
Name
Country (auto)
Status: Need to be the event status, no need to have 'active'
Type
Event Date and Time:
Latest notification
Severity
Security
Person in charge
SharePoint link

Opened
    Date
    Time
Last updated
Event link
Report link
Creator

**Response [Tab collapse as default]**
Project Code:
Program Type: Check box: Food Distribution; Mental Health; NFI; Primary Health Care; Secondary Health Care; Sexual Reproductive Health; Shelter; Tertiary / Specialized Health Care; Therapeutic Feeding; Vaccination; WAT-SAN; Other (Specify)
Free text box (Add details if any)
Start Date of the MSF Response: Pop calendar
End Date of the MSF Response: Pop calendar
Location of MSF Response: Map-driven selection
Visa Requirements: Free text box
Operational Center: Check box (note: no default selection): OCA; OCB; OCBA; OCG; OCP
Medical Materials: Free text box
Non-medical Materials: Free text box
Budget: Free text box
Donors: Free text box

**External Capacity [Tab collapse as default]**
Analysis of capacity on the ground (local and national): Free text box
Other organizations (e.g. NGO or INGO): Free text box

**Medical Figures [Tab collapse as default]**
Check box + free number box for Number of each case:
Births; Cholera Cases; Dengue Cases; Group Consoling or Mental Health Sessions; Individual Mental Health Consultations; Inpatient Cases; ITFC; Major Surgical Intervention; Malaria Cases; Measles vaccination; Measles cases; Meningitis vaccination; Migrants / refugees rescued at sea; NFI kits distributed; Outpatient Cases; SGBV Cases; Shelter kits distributed; Other (Specify)

**Staff Resources [Tab collapse as default]**
in this section, the Operator requests the ability to add individuals from local staff as follows:
NAME: Free text box
FUNCTION: drop down menu: Admin; HR; Finances; Logistics; Medical/Paramedical; Mental Health; WAT-SAN; Other
CONTACT: Free text box
COMMENT/EVALUATION: Free text box
HIRED BY MSF: Pop up calendar
NATIONALITY: Drop down menu: Local / Expat

**Reflection [Tab collapse as default]**
Practical Details / Comments: Free text box
Recommendations: Free text box

**Comment by LucieGueuning** [comment]
So all info on the window for edition need to be displayed on the event page as collapse tab

**Comment by matthewberryman** [comment]
@mehrdadgit please review https://github.com/MSFREACH/msf-reach/issues/60#issuecomment-369670636 and also work on https://github.com/MSFREACH/msf-reach/issues/301

**Comment by matthewberryman** [comment]
@mehrdadgit Can you please work on this tonight for the event *tab* on the event page in dev branch please (separate to the edit modal stuff in your other branch)

**Comment by mehrdadgit** [comment]
@matthewberryman the other branch did not touch edit modal; mainly event page and I just merged dev into that (resolving a couple of conflicts ) and sent a PR; in my opinion, it's ok to merge now.... If not I basically have to redo the things I have done in other branch... anyway have a look at PR and let me know

**Comment by matthewberryman** [comment]
@mehrdadgit sorry, earlier I just had a quick look at one of the commits (busy day across a number of projects for me) and misread where it was in the event page. Thanks for your work on this issue. I will will have a look at your PR first thing tomorrow.

**Comment by LucieGueuning** [comment]
Can this be displayed on event page and not on the pop-up window anymore? thanks.

**Comment by matthewberryman** [comment]
Yes that’s what this work does. I misread earlier per previous comments.

**Comment by matthewberryman** [comment]
@mehrdadgit for new events & events where I'm going to clear out old-style data for visas, the display reads ", required: yes" whereas it should read "".
