### ISSUE TITLE
severity sliders broken with https://github.com/MSFREACH/msf-reach/pull/590 changes

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#619]
1. Doesn't always show severity slider on addition of area.
2. If this comes up on page reload, then it doesn't save changes any more.

**Comment by matthewberryman** [comment]
Slider value and text is being saved, but slider values (aside from first one) not being saved.

<img width="665" alt="screenshot 2018-09-04 12 19 27" src="https://user-images.githubusercontent.com/2288238/45007629-013e7280-b042-11e8-8940-5fad6ede873d.png">

**Comment by qclin** [comment]
@matthewberryman  please check this commit 

https://github.com/MSFREACH/msf-reach/commit/1de3bfdaa9fe1d36627913ce345e47eaf18ef483
