### ISSUE TITLE
Request Changes for Contact Cards on Map (Landing and Event pages)

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#62]
For Contact pins on Landing Page:

Please default to off so it doesn't look so shitty.

For Contact pins on Event pages:

Please default Contact Pins in the area of the Event to ON, so that the Operator can see the contacts who are within an event theatre when click or hover.

Phase 2 dev: Please make the Contacts tab only have screen, so that map is visible (i.e. like REM so that table click highlights map and map click highlights table). Obv. this is major renovasi so just putting that Map=Table drive-ability as objective for Operators.

**Comment by matthewberryman** [comment]
Fixed in other issues.
