### ISSUE TITLE
disease sub-types missing on event edit on dev

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#620]
looks like another one broken in #590. Working in master

**Comment by matthewberryman** [comment]
Seems intermittent. Please try on copy of database for different events. Also make sure it saves properly.

**Comment by qclin** [comment]
<img width="608" alt="screen shot 2018-08-28 at 11 14 01 am" src="https://user-images.githubusercontent.com/10966917/44713491-86121500-aab3-11e8-895a-2e2f87cb86c1.png">

hmmm

**Comment by matthewberryman** [comment]
Seems to have been fixed with changes @mehrdadgit made as part of work on https://github.com/MSFREACH/msf-reach/issues/613 after I noticed this bug.
