### ISSUE TITLE
ICONS ON LANDING PAGE

### ISSUE THREAD

**Issue by clgeros** [MSFREACH/msf-reach#63]
On the landing page we should have 4 different icons (both items shown on the map and matched in the legend):

1. Contacts: https://drive.google.com/file/d/0Bw27FPU-gFxYSjk3WWxoelIxb1k/view?usp=sharing

2. Mission History / Closed Event: https://drive.google.com/file/d/0Bw27FPU-gFxYQlYxSGdlZ1ZYM1E/view?usp=sharing

3. Current Event: https://drive.google.com/open?id=0Bw27FPU-gFxYbE9tZU5TbDBUbjA

4. PDC (volcano, green level alert is the only one necessary for this week): https://drive.google.com/file/d/0Bw27FPU-gFxYb003cTE5WjU4bVU/view?usp=sharing

**Comment by clgeros** [comment]
Also please note that the icon for "mission history / closed event" has been altered so please replace the .svg. It was not rendering properly. THX!

**Comment by matthewberryman** [comment]
Regarding icons on the map:
1. This was the contacts icon we already had in place.
2. The file you sent was the same file we already had in place. Agree it could look better but short of a new file not much I can do.
3. Done; applied for all events.
4. Have updated the volcano PDC hazards, have left others in place ( too much work to kill them).

Regarding legend: 
Hopefully @talltom gets a bit of time, but main focus on legend is  #54 and I'm not sure he'll get time for that by Friday due to other commitments.

**Comment by matthewberryman** [comment]
Currently OC icons for events & missions are differently sized, will fix this, and should make the mission history icon render a bit better too. The volcano svg file sent doesn't show up on satellite view so I will revert to png version as used on PDC map for now. 
<img width="116" alt="screenshot 2017-08-22 12 12 23" src="https://user-images.githubusercontent.com/2288238/29545700-2deac5d8-8733-11e7-86f4-3d332d1896fa.png">

**Comment by clgeros** [comment]
PDC volcano .svg fixed: https://drive.google.com/file/d/0Bw27FPU-gFxYQk9yem9wUnlMRlE/view?usp=sharing

**Comment by clgeros** [comment]
Just fixed the .svg for the volcano symbol. should show correctly now.

**Comment by matthewberryman** [comment]
thanks @clgeros will give that a try shortly.

**Comment by clgeros** [comment]
I went ahead and dropped all of the PDC symbols that are currently showing on their map in the southeast asia region: https://drive.google.com/drive/folders/0Bw27FPU-gFxYSTJ0VU9hSUhJOGs?usp=sharing

We may not need to show these for tomorrow, but they are ready. We will use the cyclone symbol for cyclones, typhoons, and high winds.

**Comment by matthewberryman** [comment]
Ok I will try and get this out by tomorrow (and we are closing things out midday tomorrow prior to Friday).

**Comment by matthewberryman** [comment]
I've done #54 (have preserved separate event type layers in https://github.com/usergroupcoop/msf-reach/tree/old-legend-with-event-categories should we ever need to swap back), leaving legend icons as very low priority (i.e. not by close down tomorrow) by @talltom at later stage.

**Comment by matthewberryman** [comment]
@clgeros @LucieGueuning I have the supplied mission history icon in already. The problems here are 
1. As the image scales, the gap between the outline and the body of the icon only grows.
2. The gap is a transparent gap, so other icons e.g. contacts show up underneath and make it look red, etc.
To fix the issues I need a newer mission history icon from you.

**Comment by clgeros** [comment]
@matthewberryman the updated icon at: https://drive.google.com/file/d/0Bw27FPU-gFxYQlYxSGdlZ1ZYM1E/view?usp=sharing does not have a transparent gap between the outline and the inner circle. So, hopefully that should help!

**Comment by matthewberryman** [comment]
@clgeros that's the one I'm using. As is, when it is rendered and scaled by the browser, because the outer circle and the rest are in different vectors, the scaling is creating gaps. I will have a go at converting to png and then scaling it.

**Comment by clgeros** [comment]
Ok. Sorry, I know the first time I loaded the .svg for that one, the outer shape was transparent (no white inside the black outline)... so I fixed and reposted that one, but if that doesn't solve it, I can send you a .png no problem.

**Comment by matthewberryman** [comment]
@clgeros Ok I'm not sure that the Google drive link has successfully taken it, then—when I download it I get the exact same file (verified via two different means). Can you email me the svg and png so I can have a play with both then.

**Comment by clgeros** [comment]
No problem. Email sent. I also included a new version of the "current event" with a white outline... just because the point of the tag is getting lost on the satellite image. Try if you have time, if not it's ok.

**Comment by matthewberryman** [comment]
Ok now I have it - the historical icon you sent in email is different to the one on the google drive link. All this wasted energy because of a quirk in Google Drive itself. :/ 
I will update both now and see how we go

**Comment by clgeros** [comment]
So sorry! It looks correct on my end :/

**Comment by matthewberryman** [comment]
Not your fault, just Google Drive isn't registering the updated version. The ones you sent me are deploying now (deployment takes several minutes). I'll let you know when it's done, but be sure to do a shift (Win)/ command (Mac) reload to get it to pick up the new ones.

**Comment by matthewberryman** [comment]
Done. And looking better. Hooray! I will resize them ( #71 ) tomorrow.

**Comment by clgeros** [comment]
Awesome! Looks so much better! Now that we see that, maybe the mission histories should be slightly "ghosted". so they are a little less bold on the screen.. 80% opacity? Is that possible?

**Comment by matthewberryman** [comment]
I can set opacity of map icons using http://leafletjs.com/reference-1.2.0.html#marker-opacity (just putting the link here for my reference when I work on this early tomorrow a.m.)
