### ISSUE TITLE
Errors, duplication on event open and on past response editing

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#632]
1. I'm getting 400 bad request errors on mission editing on the landing page. `{"statusCode":400,"error":"Bad Request","message":"child \"eventId\" fails because [\"eventId\" is required]","validation":{"source":"body","keys":["eventId"]}}`. Seems the API (possibly?) and client side code was broken.
2. Also reports that information entered for one is being copied across past responses (ref. email trail to be sent in a minute).

**Comment by matthewberryman** [comment]
Just noting that 2. may be a client side thing with Vue.js only (?)

**Comment by matthewberryman** [comment]
Ok I had a skype session with the user and, noting they are using Safari, 
Confirmed that (2) is (or was - due to caching) an issue in master branch. Not sure if client side only (i.e. is it not clearing stuff between modals?). Workflow was edit past mission on landing page, make some changes (e.g. description) and then info was duplicated into other past missions.

May be similar issue causing event duplication although couldn't reproduce on test side nor on dev; workflow for that was (a) open event, (b) edit on event page and set status to completed then (c) close event (bottom of event page).

(1) is something separate was seeing in dev branch on dev site, but my feeling is to leave this as one issue to cover testing around past mission editing.

**Comment by matthewberryman** [comment]
I'm having trouble reproducing the (master branch) issues - be sure to test on Safari especially.

**Comment by qclin** [comment]
@matthewberryman  i tested for (1) 
saved okay on dev 
https://github.com/MSFREACH/msf-reach/blob/dev/public/events/mission.html#L737
grabs eventId from the url hash like everywhere else.

**Comment by matthewberryman** [comment]
@qclin @mehrdadgit @talltom any testing on (2) done?

**Comment by matthewberryman** [comment]
Ok I haven't figured out the duplication on event edit, however I have figured out the duplication (x2 at least) on event creation and close. It's because you can set status to completed and that triggers a close of event (copy to missions) and then also click on close button at bottom of page and that also triggers a close of event (i.e. another copy to missions).

**Comment by matthewberryman** [comment]
So we need to stick with one way of closing it, make sure date is prompted for correctly (part of #633 ) and then make sure information is copied over correctly (#635 ) and that may also help with some of #633 too although there are some completely separate subissues on #633

**Comment by matthewberryman** [comment]
Ok, method (a) is copying over types and other info correctly but method (b) is not, so for now I will remove that button and inform users, then we need to tidy up the js code later. That then leaves some of #633 to go.

**Comment by matthewberryman** [comment]
Just noting (after speaking with @mehrdadgit ) neither of us have been able to repro the mission editing issue so considering that closed. Mission opening (on event closure) duplication fixed in c5a1691

**Comment by matthewberryman** [comment]
https://github.com/MSFREACH/msf-reach/commit/d96be7aabeb6b1c7893adf5feb5b5147d7d33eb5 allows correct editing (and tested) despite [false not being supported according to jquery docs](https://api.jquery.com/jquery.extend/). I think we need a proper fix (the extend seems to be there to  fill out details where blank) so something along those lines.

@mehrdadgit

**Comment by mehrdadgit** [comment]
Thanks @matthewberryman done in above commit and please test further

**Comment by matthewberryman** [comment]
Thanks. Have tested different use cases and `git cherry-pick`ed into master. https://github.com/MSFREACH/msf-reach/commit/d96be7aabeb6b1c7893adf5feb5b5147d7d33eb5 was working but https://github.com/MSFREACH/msf-reach/commit/51167ed4556077139eacdd11a60448a026df7db8 has the advantages of:
1. Using a documented jquery feature.
2. Making more sense in terms of logic.
3. Explains why original case wasn't working (because you need to merge missions and default event into an empty object each time, not default event object that then gets over-written).
