### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#633]
Can we take a look to ensure that all dates entered are being stored correctly and displayed correctly, especially on Safari (which doesn't always handle ISO 8601 properly, dependent on version).

**Comment by mehrdadgit** [comment]
This was both chrome and safari issue. 

I fixed the date not saving/ showing correctly in the above commit for mission modal. There is still an issue that in edit-mode `<date-picker>` does not prefill with the current datetime!? still looking into it...

@qclin I've ran out of time today; could you please double check all other modals/event edits etc and make sure that date save/display functionality is working as it should ? (Note in DB sometimes dates are stored in different formats e.g. sometimes in 'DD/MM/YYYY' and sometimes as a full ISO string; I have handled both cases in my above commit (compare `formatDateOnly` and `formatFullDate`)

Also (re https://github.com/MSFREACH/msf-reach/commit/b7b04d7fb926d9f537490d586a625a0ed480734e ) @qclin is there an easy way to update landing page without hard refresh on mission edits? if not could we do the page refresh just when the modal is closed; it is very annoying at its current state.

**Comment by qclin** [comment]
@mehrdadgit you can close the modal and call load mission table again

**Comment by matthewberryman** [comment]
@mehrdadgit @qclin Just noting this issue applies to *all* dates not those on missions modal. There are a number of issues still:
* Suggested close date on event close has month and day swapped around.
* Event start and close dates not copied to any mission fields on close.
* Mission has uneditable open and close on left hand side of modal and these aren't correct.
* Duplication of event closure on mission modal.
<img width="1257" alt="screenshot 2018-09-10 09 21 31" src="https://user-images.githubusercontent.com/2288238/45270027-3f70e180-b4db-11e8-8a4f-7840b19ae1fa.png">
<img width="895" alt="screenshot 2018-09-10 09 22 13" src="https://user-images.githubusercontent.com/2288238/45270029-4697ef80-b4db-11e8-87f1-c60358ecc347.png">

**Comment by matthewberryman** [comment]
Also opened date invalid
<img width="249" alt="screenshot 2018-09-10 09 59 08" src="https://user-images.githubusercontent.com/2288238/45270372-2fa7cc00-b4e0-11e8-8b92-74dffd70a292.png">

**Comment by matthewberryman** [comment]
Re-opening to track display of mission end, if present, otherwise close date, properly in table.

**Comment by matthewberryman** [comment]
@LucieGueuning ready for review in test environment

**Comment by LucieGueuning** [comment]
wording should be (for consistency):
- End date of MSF response
- Closure Date of event

**Comment by matthewberryman** [comment]
wording changes made in 212ef98
