### ISSUE TITLE
editing info not saved

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#641]
"I created a new event, then it appears in the Ongoing responses. I click that to open and edit it (putting in the start and end date of MSF response and checking the box of the Operational Centre. Then I save and close the event. However, when I click on the event's flag to open it up again, I notice that the dates and OC information are not captured; and I have to click the edit button and add it in."

**Comment by qclin** [comment]
@matthewberryman where do you first edit?

**Comment by matthewberryman** [comment]
On event page.

**Comment by matthewberryman** [comment]
'I'm working on "Ongoing responses" now.... and noticed that when I edit the "Operational centre" and save it, the info doesn't appear.'

**Comment by matthewberryman** [comment]
@qclin can you please fix this urgently

**Comment by qclin** [comment]
Mathew there's a pull request from 27 days ago that already resolve the issue with OCs and location
https://github.com/MSFREACH/msf-reach/pull/642
#642 

Please merge that branch first

**Comment by matthewberryman** [comment]
My bad for missing the notification on email for that one. I’ll get onto it tomorrow.

Sent from my iPhone

On 8 Oct 2018, at 21:05, Qiao Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


Mathew there's a pull request from 27 days ago that already resolve the issue with OCs and location
#642<https://github.com/MSFREACH/msf-reach/pull/642>

Please merge that branch first
