### ISSUE TITLE
paragraph mark in the text box

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#644]
Issue: in the editing box, the paragraph marks are properly displaced, but in the event page the paragraph marks are gone.
Expected change: Basic text formatting such as paragraph mark, bold, italics can be displaced in the text.

**Comment by matthewberryman** [comment]
@LucieGueuning to work with users and supply a list of all text fields required to support formatting as part of https://github.com/MSFREACH/msf-reach/issues/572 (now covers more than just notifications)

**Comment by LucieGueuning** [comment]
Still unable to do bullet points and paragraphs in the notifications (previous feedback given by me and Ken).  Even if we segment info while editing, it comes out as a big chunk when saved.  It's not reader-friendly.

**Comment by matthewberryman** [comment]
@LucieGueuning as noted this is covered by #572 , see also work done in https://github.com/MSFREACH/msf-reach/pull/624
