### ISSUE TITLE
RSS feed not updated? (not too sure)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#647]
![image](https://user-images.githubusercontent.com/25951555/45807249-fc70f400-bcba-11e8-9097-798f1b4c6937.png)

**Comment by matthewberryman** [comment]
I could see this in the first page load but then not on refresh, so it's just a caching issue. I have disabled all the server side caching in 44cce93389ed3d1da63c08d7c8fc07d6bcad353b and confirmed that the server is also telling the web browser not to cache any data, but there's no strict guarantee around web browser behaviour and that's not something I can control.
