### ISSUE TITLE
Toolbox tabs

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#65]
Create a toolbox tab with 'Create an event' and 'create a contact'

**Comment by matthewberryman** [comment]
We already have links for these in the menu, and the additional tabs requested in https://github.com/usergroupcoop/msf-reach/issues/60 won't leave room for additional tabs there. If you want tabs somewhere else please send through a design and reopen this issue.

**Comment by LucieGueuning** [comment]
Should I move this issue on Design?

**Comment by matthewberryman** [comment]
@LucieGueuning @clgeros if you could work together and send me a picture / diagram of how you want it to look then I can work on that.
