### ISSUE TITLE
Cursor for every field of info (as notification)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#655]
In the "Deployment" part of the External Capacity section as the one we had in notifications.  Coming back from another tab, the cursor goes back to the start of the text you are editing, so you have to move manually move the cursor to the end of the text.  Annoying.

**Comment by matthewberryman** [comment]
Fixed https://www.dropbox.com/s/nlsq3vxdww173rw/cursor%20bug.mov?dl=0
