### ISSUE TITLE
Bug in the menu selection

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#658]
It keeps disappearing if you click more than once.

**Comment by matthewberryman** [comment]
@LucieGueuning to provide details:
* Which menu? One at top right (which I have tested and is work)? Dropdown for contact category? etc.
* Browser incl. version number (help/browser name -> about in menu).

**Comment by LucieGueuning** [comment]
the one on bottom left (for layer on and off)
any browser. It happens in other use on Mac, PC, Chrome or safari.

**Comment by matthewberryman** [comment]
I can't reproduce this issue. The layer menu stays on when I click more than once. It only disappears when I move off of it, and reappears when I mouse over it. See https://www.dropbox.com/s/943yqdkf9lqg5qq/658_video.mp4?dl=0

**Comment by LucieGueuning** [comment]
Please email send with video

**Comment by matthewberryman** [comment]
@LucieGueuning and I had a look together on her computer and could no longer reproduce the bug, hence closure
