### ISSUE TITLE
Share function for contact not working (private and share)

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#660]
- Share function: name coming in and suggestions from address book not coming
- Private says 'no' in table but in the popup says 'yes'. Confusion.

**Comment by matthewberryman** [comment]
Table (on landing and events pages) was always showing no, however privacy was maintained and popup was correct. Share function issue is on landing page.

**Comment by matthewberryman** [comment]
@LucieGueuning ready for testing - I have put this in master branch for you to test as I cannot test the autocompletion feature on the test environment with the guest accounts, and it won't work on dev as that's linked to Cognito not AD.

**Comment by LucieGueuning** [comment]
It takes some time but it is working.
