### ISSUE TITLE
allowing to change the type for mission history

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#664]
Feedback from Fei: Is it possible to make changes to the website to allow edits on the field “Type of emergency/nature” for Past responses?
<img width="750" alt="editing type for closed missions" src="https://user-images.githubusercontent.com/25951555/47301685-60b70880-d617-11e8-93e5-f3532693c7d2.png">

**Comment by mehrdadgit** [comment]
Done @matthewberryman note since type is not part of `metadata` for event and hence was not being copied over to the missions.properties; I am backfilling it in https://github.com/MSFREACH/msf-reach/commit/2c839902d3099fce5dc3dd684777b3925479365b as `event_type` in missions.properties
