### ISSUE TITLE
alignment of share buttons needs fixing

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#667]

**Comment by matthewberryman** [comment]
<img width="643" alt="screenshot 2018-10-28 10 54 05" src="https://user-images.githubusercontent.com/2288238/47630515-55268d00-db95-11e8-9f9c-1494bcd33de1.png">

**Comment by mehrdadgit** [comment]
Fixed in a very tricky way ;) 
For future better to customise more or create our own share buttons. ShareThis injects a lot of elements and it interferes with vue.
