### ISSUE TITLE
Contact Card - field improvement

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#67]
If 'current MSF Staff' is checked, then a drop down with the following field 
OC/PS/BO/Mission - free text
Current employment status
Current position - job title

**Comment by matthewberryman** [comment]
@LucieGueuning @anexact was this confirmed in writing following previous meeting as being part of phase 1? If not, please remove from phase 1 completion milestone, just as a point of tracking.

**Comment by LucieGueuning** [comment]
Yes for Phase 1 completion, as it is part of the contacts cards requirements. 
Although, I removed some fields to make it easier for you. 
Thanks!

**Comment by matthewberryman** [comment]
@mehrdadgit Just note https://github.com/MSFREACH/msf-reach/commit/2d9a4689f4b8bbe5c6af45efedaaab69c99476d3 - I will catch both MSF Peer and Current MSF Staff (or anything that includes the string MSF) for affiliation.

**Comment by mehrdadgit** [comment]
Done @matthewberryman  ready for review.. we might want to remove specialty from that div in the contact modal https://github.com/MSFREACH/msf-reach/commit/2d9a4689f4b8bbe5c6af45efedaaab69c99476d3  cause does not seem to be MSF-fields-related ?

**Comment by matthewberryman** [comment]
Thanks @mehrdadgit for this and your other work today.
A couple of comments:
* We should also have this for MSF peer as well.
* We need to capture (medical) speciality for MSF staff & peers (so it will display in modal per 2d9a4689f4b8bbe5c6af45efedaaab69c99476d3 ). 

I am just about to have a super early night (after a super late one last night) but have a bit of time in the morning to add these changes in if you don't have time now.

**Comment by matthewberryman** [comment]
Also needs some UI fixes to handle cases where speciality was imported from spreadsheet for non-MSF people. Working on wrapping this all up now.
