### ISSUE TITLE
severity slider issues

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#677]
Various bugs in set up and handling of sliders. Most now fixed (commit to come soon) with exception of the following (@mehrdadgit can you please have a look asap):
On addition of the first area to a new event, the slider in editing doesn't show up until save and then re-edit.

**Comment by mehrdadgit** [comment]
on it

**Comment by mehrdadgit** [comment]
A fix is done on issues/174branch.

Some observations after spending  around 2 hrs on this: 

* if `metadata.severity_measures` are per area why do we have 2 separate arrays and do the complicated work of syncing `metadata.areas` and `metadata.severity_measures`. Severity info could go inside area..
* Going forward we can avoid jquery ui silder and use the basic `input type="range"` and apply some style tweaks on it. It would make the code much shorter/simpler.

**Comment by matthewberryman** [comment]
> if metadata.severity_measures are per area why do we have 2 separate arrays and do the complicated work of syncing metadata.areas and metadata.severity_measures. Severity info could go inside area..

Yes, agreed.

> Going forward we can avoid jquery ui silder and use the basic input type="range" and apply some style tweaks on it. It would make the code much shorter/simpler.

The trouble is you can't do this in a cross-platform way easily, see https://www.hongkiat.com/blog/html5-range-slider-style/ for one of the issues (there were others I found...)
