### ISSUE TITLE
possible to zoom out too far on map

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#680]
Results in lat,lng bounds being out of range resulting in broken API calls.
![48562415-0e9d9600-e8ea-11e8-9909-6daeac419767](https://user-images.githubusercontent.com/2288238/48585249-2fb0c600-e980-11e8-87cc-b7644f16e79e.png)

**Comment by matthewberryman** [comment]
dupe of #571

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/49532226-f51db780-f8b3-11e8-9064-fc01d9531f5c.png)
Still the case

**Comment by matthewberryman** [comment]
Duplicate of #571

**Comment by matthewberryman** [comment]
@LucieGueuning this is the same issue as #571 - please continue discussion on that thread.
