### ISSUE TITLE
cognito - no authenticated user

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#688]
https://github.com/MSFREACH/msf-reach/commit/0a5579b8e4eb5f86e178713a5e41d1a259600b6c fixes the bug in the error handling at least, but the error is still there, namely https://github.com/MSFREACH/msf-reach/blob/0a5579b8e4eb5f86e178713a5e41d1a259600b6c/app/src/store/auth.module.js#L90 is throwing "not authenticated". I don't see how your use of auth.module in https://github.com/MSFREACH/msf-reach/blob/0a5579b8e4eb5f86e178713a5e41d1a259600b6c/app/src/store/index.js#L14 is going to connect to the rest of your Cognito code, noting that cookies (which you seem to be using per other code) won't work per https://github.com/aws-amplify/amplify-js/issues/812. Suggest you discontinue work on this as it's wasted effort and just start on the AD integration work, which will need to be done anyway.

**Comment by qclin** [comment]
resolved, when public key was shared by matthew.
no longer use cookies to store tokens on client browser. front-ends sends token via Authorized header per request 

https://github.com/MSFREACH/msf-reach/commit/bd60ffae44176bcccf9e13995a2a34c438486f02
