### ISSUE TITLE
Contacts Table = Map Nav

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#69]
Request for Enhancement re: Contacts:

- can Contact table not open to whole page; instead, can Contact table open partially, showing map (similar to REM RW table to map for PB.id)?
- suggest that Contact table and Contact icon both contain a "View Full Details" button, which would pop up a complete Contact card for ALL contact info for that informant;
- several other discussions to be had with MB about Contact discoverability

**Comment by matthewberryman** [comment]
Already done / covered elsewhere
