### ISSUE TITLE
uploads not working

### ISSUE THREAD

**Issue by qclin** [MSFREACH/msf-reach#690]
Download URL request generated in the backend 
https://github.com/MSFREACH/msf-reach/blob/ux/navigation/src/api/routes/utils/index.js#L60

Download Okay but rendering in the browser doesn't work 
https://github.com/MSFREACH/msf-reach/blob/ux/navigation/app/src/components/CountryDetails.vue#L73

To test
Login to UX site as matthewberryman
Under Event Detail  > Country Details (expand on of the sections) > Upload file 

<img width="1197" alt="screen shot 2019-02-15 at 3 22 21 am" src="https://user-images.githubusercontent.com/10966917/52830473-1deed400-30d1-11e9-81b1-052a990a8e7c.png">
 
https://ux.msf-reach.org/#/events/257/country-details

**Comment by matthewberryman** [comment]
At first glance at the code it seems it's as I thought in that the template gets rendered first (when downloadUrl isn't set), but @mehrdadgit knows his way around vue.js much better than me.

**Comment by mehrdadgit** [comment]
Had a look; my best guess is that the signed download is fine but signed upload is not working properly; 
To verify can somebody check the S3 bucket manually to see if e.g. this file is properly uploaded:
`msf-reach-file-uploads.s3.ap-southeast-1.amazonaws.com/countryDetails/PH/mission/f417d053-2876-4663-b03c-9ebb6b436e72_logo.png`
(making sure you can see the photo when you download it manually from S3 as the signed donwload link returns a 13-byte corrupted empty file...

if so, the problem could be somewhere around here which would need a deeper look: https://github.com/MSFREACH/msf-reach/blob/ux/navigation/app/src/components/CountryDetails.vue#L216

EDIT: see below the content of logo.png I uploaded, the downloaded and changed the extension to .txt , looks like a JS object : 
![image](https://user-images.githubusercontent.com/7603978/52834187-99ce3800-3134-11e9-891d-823207fd3596.png)

**Comment by matthewberryman** [comment]
@qclin, @mehrdadgit is correct, the upload process is broken—you're sending `[object File]` not the file itself. Additionally you probably want to wait for all files to finish uploading before calling `save()` rather than calling it for each one.

**Comment by qclin** [comment]
@mehrdadgit  thanks, i switch the call to ajax and it works now to upload file. 
Still have a bug with different file types 

pdf & jpegs renders okay with the signedURL 

but for the following file types it's still returning ACCESS DENIED 
png, doc, excel 

can you take a look under 
events/257/notifications

**Comment by qclin** [comment]
@matthewberryman @mehrdadgit  thanks 
i reverted back to ajax for uploading, axios seem to send double request with [object: file] 

it works now, but for file names with spaces, s3 is still returning Access denied, will close this once that's resolved

**Comment by qclin** [comment]
resolve in 90aad8a2502de1cb6279817c27b4070ed18040da
