### ISSUE TITLE
Request for improved Contact discoverability / searchability

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#70]
Request from Operator to add SEARCH function to contacts at Landing Page level and Event level; currently limited in ability to discover relevant contacts, and this is a vital function for the platform that could use strategic discussion as well as UX improvement with search function.

**Comment by LucieGueuning** [comment]
Request from boss. Could we have for column 'What is your current Affiliation (employer-company name)?' a free search bar? needed

**Comment by matthewberryman** [comment]
This is a new feature (hence) tag- we need to start using milestones feature of github to track urgency, although on this one honestly we will not get this done by Friday.

**Comment by LucieGueuning** [comment]
need to be there for presentation.
