### ISSUE TITLE
Latest updates on landing page

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach#77]
Can we have a box containing the latest actions (date, time and by whom) on landing page? 

Location : up to current event list

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/36840303-65a8d164-1d3c-11e8-99be-4a38091b5a84.png)


We need to make this changes for the presentation

**Comment by matthewberryman** [comment]
Location done as part of area support. Latest actions covered by #439
