### ISSUE TITLE
Event Creation / Event Name Generating / Event Card 

### ISSUE THREAD

**Issue by clgeros** [MSFREACH/msf-reach#78]
When creating an event, the first selection should be "event type" and **instead of "drop down" selection would be best to select from "event type" icon list** like: 
<img width="330" alt="screen shot 2017-08-22 at 4 07 10 pm" src="https://user-images.githubusercontent.com/22763936/29555082-03fd1e30-8754-11e7-97b0-9f8c5a987321.png">

Next, "Event location" to be generated by map selection

Then, "Date" to be automatically generated by platfrom.

**"Event Name" would then be created automatically by these three fields: Type_Location_Date**

**When "events are listed in column, "event type" icon should accompany the name–same as the quick view "event card" that shows when an event is selected on the map**, like:

<img width="267" alt="screen shot 2017-08-22 at 4 11 09 pm" src="https://user-images.githubusercontent.com/22763936/29555227-8f7aaa5e-8754-11e7-9fb3-8575050ee352.png">

_But, instead of showing the latest notification for that event, it could have the short (140 character) summary/description._

**Comment by matthewberryman** [comment]
* There's not enough room to display icons in the input form, and 
* adding date to the twitter search would break it (short of better twitter search, planned for phase 2, plus 
* adding the location is something that would also break the twitter search (short of geocoding as planned for phase 2).
Thus the only remaining thing that can be done in phase 1 is icon display in map popup. 

cc @LucieGueuning

**Comment by LucieGueuning** [comment]
No. Twitter is not a constraint anymore as we are going to re-work on a better twitter search. So if you can make it for date and location as well, it should be great. Many thanks!

agreed that we will work on better twitter search for Phase 2 (we shouldn't have on Twitter the name generated by system as keywords for research). However, we will need to include the constraint of a name generated by system as the following template : **Type_Location_Date** when searching for the best solution for Twitter search.

**Comment by LucieGueuning** [comment]
![image](https://user-images.githubusercontent.com/25951555/31109513-e63747f4-a832-11e7-83b0-af1cbc150bcb.png)

It is already the case, no?

**Comment by matthewberryman** [comment]
I can't make it with location and date as phase 1 twitter will return no / almost no results; also having underscores forces twitter to return no results, as you can see in the screenshot—this is the worst solution for twitter search. I will actually need to revert this back for phase 1.

**Comment by matthewberryman** [comment]
Or I suppose I could remove everything past the first underscore for twitter search. Let me check.

**Comment by LucieGueuning** [comment]
Should we hold off Twitter search for now as we need to work more on it for Phase 2. 
But instead complete entirely this issue #78 as Christina explained it.

**Comment by matthewberryman** [comment]
The current ones with underscores have been entered with old code (changed to avoid breaking twitter search). I will remove the name field and autogenerate as desired, and then for twitter search just use type (and subtype if present) separated by spaces, as I think the best solution here. Then the icon can be added to the event pop up on the map by @rcdelfin or @mehrdadgit (note the icons are under public/resources/images/icons/event_types/ and I have sanitised filenames in ff3fdd3 so it should be easier to write code for event type or subtype to map those fields onto filenames).

**Comment by matthewberryman** [comment]
@rcdelfin @mehrdadgit disregard comments, I will do icons in event popup on map.

**Comment by matthewberryman** [comment]
@LucieGueuning done as requested bar selection from icons (difficult due to ui constraints also multi-level type/subtype breakdown- can explore options in phase 2). The name is generated as requested, and icons display on popups as also requested. Twitter search uses either type or subtype (if present) to avoid breaking basic twitter AI with this update. Tested all of this locally, and deployment will happen in several minutes from now.

**Comment by matthewberryman** [comment]
Twitter search needs a bug fix for some cases, will work on that after #104 changes

**Comment by matthewberryman** [comment]
Not working where a subtype is specified

**Comment by matthewberryman** [comment]
cc @clgeros @LucieGueuning also I will need to tidy up the database

**Comment by matthewberryman** [comment]
@clgeros @LucieGueuning had to restore from my copy of the database taken a couple of days ago - was too fiddly to recreate just the events and associated reports alone (and any contacts / new reports for existing events added since then is just testing data).
