### ISSUE TITLE
support different roles

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#79]
https://github.com/usergroupcoop/msf-reach/issues/75

**Comment by LucieGueuning** [comment]
linked to #57

**Comment by matthewberryman** [comment]
To-do:
1a. Change API to have two authentication strategies, one as is where the group ID is checked per code starting https://github.com/MSFREACH/msf-reach/blob/2a4c939212f38bb7a8e6215ee0334f30f0ebd3fa/src/server.js#L73 , that is used on all protected API requests with exception of protected GET requests, where the other authentication strategy, that ignores group ID, is used.
1b. If not allowed, make sure 403 is returned as http error code.
2. Client side, if the user clicks on a UI element that makes a protected PUT/PATCH/etc. request, when the 403 is returned, catch that and pop up a modal to read "For edit access please contact `<a href="mailto:lucie.gueuning@hongkong.msf.org">Lucie Gueuning</a>"

**Comment by matthewberryman** [comment]
@stefan-devika please do this in the devika branch (note I just updated this with latest dev work, so do a `git pull` first before commencing work)

**Comment by LucieGueuning** [comment]
Same button but message for viewers: You do not have the permission, please contact us (mailto:lucie.gueuning@hongkong.msf.org) for edit access. OR 'For edit access, please contact us'. whatever  is the best for you.

**Comment by matthewberryman** [comment]
@stefan-devika when you're done (incl. fixing eslint issues https://travis-ci.org/MSFREACH/msf-reach/builds/358238850 ) please submit a pull request for devika -> dev branch
