### ISSUE TITLE
Report Card Error re: Search Bar

### ISSUE THREAD

**Issue by anexact** [MSFREACH/msf-reach#94]
When a REACH Report Card is received via Twitter, user can open the link, however, if the search bar function above the map in engaged, the Previous / Next buttons disappear, making it impossible to move ahead or go back in the cards. 

![image1 1](https://user-images.githubusercontent.com/20785542/29650040-c79144a8-88ca-11e7-8d63-507f1c2250af.PNG)
![image2](https://user-images.githubusercontent.com/20785542/29650058-e0bcddf2-88ca-11e7-9b0f-d7e31463f5e7.PNG)
![image1 2](https://user-images.githubusercontent.com/20785542/29650069-ebd17112-88ca-11e7-8310-0d9335a52047.PNG)

**Comment by matthewberryman** [comment]
Will look at this, may have to disable google search bar as quick fix.

Sent from my iPhone

On 24 Aug 2017, at 12:52, Etienne Turpin <notifications@github.com<mailto:notifications@github.com>> wrote:


When a REACH Report Card is received via Twitter, user can open the link, however, if the search bar function above the map in engaged, the Previous / Next buttons disappear, making it impossible to move ahead or go back in the cards.

[image1 1]<https://user-images.githubusercontent.com/20785542/29650040-c79144a8-88ca-11e7-8d63-507f1c2250af.PNG>
[image2]<https://user-images.githubusercontent.com/20785542/29650058-e0bcddf2-88ca-11e7-9b0f-d7e31463f5e7.PNG>
[image1 2]<https://user-images.githubusercontent.com/20785542/29650069-ebd17112-88ca-11e7-8310-0d9335a52047.PNG>
