### ISSUE TITLE
shortid issues

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#97]
See https://github.com/urbanriskmap/cognicity-server/issues/53 for details

**Comment by talltom** [comment]
@matthewberryman I propose that we move to postgres UUIDs?

This is my preference given that we've agreed to keep PG/Node stack. If you agree I'll start work on a branch of the schema.

**Comment by matthewberryman** [comment]
@talltom can you please make sure changes are either compatible with existing database entries or otherwise provide a script in msf-reach-schema repo to update the database as part of this work

**Comment by talltom** [comment]
Yep - upgrade scripts added to schema repo and in progress :)

https://github.com/MSFREACH/msf-reach-schema/tree/dev/updates

**Comment by talltom** [comment]
PR https://github.com/MSFREACH/msf-reach/pull/215

**Comment by matthewberryman** [comment]
This was done quite a while back
