### ISSUE TITLE
MapSwipe layer - OSM data

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#99]
How can we add and integrate a layer of MapSwipe on landing page?
https://github.com/mapswipe
cc @LucieGueuning

**Comment by LucieGueuning** [comment]
Where there are building but no map (a way of notifying the users that there is project to map by missing map on OSM but not yet data on it).

**Comment by matthewberryman** [comment]
MapSwipe goes to OSM which we now have as a layer.
